In [2]:
import pickle
with open('df_scaled_UTD.pickle','rb') as f:
    df_scaled_UTD = pickle.load(f)

In [3]:
df_scaled_UTD

{'Food':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.042257  0.056702  0.043803  0.081957  0.085369
 2010-05-27  0.063952  0.057396  0.044945  0.089734  0.084190
 2010-05-28  0.035991  0.065028  0.042088  0.095426  0.082391
 2010-05-31  0.025994  0.076824  0.053660  0.102915  0.089309
 2010-06-01  0.020917  0.068842  0.048728  0.103992  0.088413
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.048431  0.384509  0.392137  0.429287  0.425930
 2022-07-20  0.063502  0.407711  0.393965  0.438850  0.407666
 2022-07-21  0.049059  0.389005  0.378650  0.430612  0.405342
 2022-07-22  0.072508  0.382899  0.371164  0.428539  0.399641
 2022-07-25  0.004277  0.380956  0.370421  0.430324  0.397815

 [3002 rows x 5 columns],
 'Clothing':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.065029  0.011215  0.010954  0.021589  0.014875
 2010-05-27  0.151195  0.011669  0.010636  0.018936  0.013748
 2010-05-28  0.114483  0.011707  0.009274  0.021646  0.012696
 2010-05-31  0.071691  0.010289  0.010860  0.022158  0.017598
 2010-06-01  0.108919  0.012596  0.009162  0.020054  0.010123
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.077276  0.706283  0.721963  0.721938  0.722040
 2022-07-20  0.099751  0.732383  0.736891  0.736533  0.728237
 2022-07-21  0.070956  0.727654  0.746035  0.740703  0.738943
 2022-07-22  0.045146  0.736922  0.740623  0.744683  0.736501
 2022-07-25  0.000000  0.735787  0.742303  0.744683  0.746643

 [3002 rows x 5 columns],
 'Chemical':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.167848  0.000000  0.000000  0.000000  0.000000
 2010-05-27  0.170496  0.001486  0.002279  0.001901  0.002599
 2010-05-28  0.255567  0.009877  0.009316  0.006131  0.009724
 2010-05-31  0.105342  0.012888  0.013474  0.014776  0.012850
 2010-06-01  0.084962  0.014133  0.015113  0.014204  0.015652
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.086274  0.336813  0.333213  0.336985  0.333929
 2022-07-20  0.095430  0.346971  0.344209  0.349002  0.349560
 2022-07-21  0.110618  0.349380  0.356563  0.354111  0.361741
 2022-07-22  0.123400  0.356085  0.366399  0.361427  0.357315
 2022-07-25  0.000000  0.352993  0.355883  0.358403  0.353255

 [3002 rows x 5 columns],
 'Medicine':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.111497  0.000975  0.000072  0.000000  0.000000
 2010-05-27  0.076624  0.000000  0.000000  0.000157  0.001082
 2010-05-28  0.154472  0.001830  0.001135  0.002055  0.002078
 2010-05-31  0.059157  0.002350  0.001880  0.002537  0.002976
 2010-06-01  0.048007  0.002864  0.002025  0.002982  0.002901
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.020757  0.707096  0.704295  0.730875  0.700920
 2022-07-20  0.020793  0.710045  0.704048  0.735744  0.705051
 2022-07-21  0.013721  0.706296  0.700348  0.727995  0.696292
 2022-07-22  0.012725  0.697248  0.698671  0.728624  0.699029
 2022-07-25  0.001274  0.700647  0.698523  0.731084  0.702413

 [3002 rows x 5 columns],
 'Non_Metal':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.007824  0.000810  0.000000  0.000000  0.000000
 2010-05-27  0.006572  0.000000  0.003019  0.000754  0.003656
 2010-05-28  0.008909  0.006072  0.005246  0.002366  0.001971
 2010-05-31  0.007069  0.002378  0.001617  0.001594  0.001600
 2010-06-01  0.010493  0.001737  0.002920  0.002383  0.003235
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.004607  0.640463  0.646347  0.647678  0.651802
 2022-07-20  0.011045  0.665812  0.669147  0.672621  0.673248
 2022-07-21  0.007001  0.676016  0.669774  0.679684  0.674091
 2022-07-22  0.010026  0.677314  0.671786  0.671335  0.663982
 2022-07-25  0.000622  0.667026  0.660568  0.675964  0.666880

 [3002 rows x 5 columns],
 'Metal':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.046134  0.638395  0.641917  0.645939  0.644592
 2010-05-27  0.038383  0.637201  0.654441  0.652254  0.666106
 2010-05-28  0.031218  0.682757  0.674435  0.683900  0.680921
 2010-05-31  0.009931  0.669174  0.669077  0.680049  0.685193
 2010-06-01  0.014786  0.679596  0.665308  0.677070  0.669662
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.029213  0.244306  0.235338  0.254884  0.242500
 2022-07-20  0.033855  0.254123  0.237958  0.258582  0.245638
 2022-07-21  0.026909  0.246106  0.238408  0.256629  0.250241
 2022-07-22  0.035841  0.251873  0.243197  0.263152  0.251789
 2022-07-25  0.008111  0.253918  0.244752  0.266642  0.253671

 [3002 rows x 5 columns],
 'Machine':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.044926  0.453312  0.460286  0.475379  0.482622
 2010-05-27  0.068861  0.475767  0.509656  0.505728  0.520254
 2010-05-28  0.034065  0.535228  0.512656  0.548986  0.522363
 2010-05-31  0.030935  0.516903  0.537450  0.551607  0.561201
 2010-06-01  0.050590  0.562059  0.555889  0.592015  0.550081
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.024619  0.475603  0.465141  0.507751  0.484155
 2022-07-20  0.021200  0.496472  0.475042  0.521629  0.490647
 2022-07-21  0.023838  0.495104  0.482189  0.521287  0.494426
 2022-07-22  0.024980  0.494065  0.477770  0.524479  0.487223
 2022-07-25  0.009431  0.485176  0.476733  0.520574  0.494755

 [3002 rows x 5 columns],
 'Electronic':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.333221  0.118296  0.119514  0.122940  0.127704
 2010-05-27  0.326479  0.120054  0.123250  0.129839  0.131456
 2010-05-28  0.331900  0.129826  0.125950  0.127233  0.126256
 2010-05-31  0.227260  0.120764  0.124358  0.129981  0.132955
 2010-06-01  0.206178  0.129577  0.130086  0.138264  0.136632
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.109038  0.730008  0.729319  0.763404  0.757217
 2022-07-20  0.132803  0.737739  0.739613  0.773259  0.771115
 2022-07-21  0.083117  0.739374  0.745094  0.779883  0.783920
 2022-07-22  0.074844  0.747849  0.746649  0.781459  0.775175
 2022-07-25  0.006095  0.731123  0.732652  0.767267  0.762761

 [3002 rows x 5 columns],
 'Construction':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.041874  0.497826  0.488781  0.486972  0.499535
 2010-05-27  0.036684  0.492991  0.495701  0.490781  0.499553
 2010-05-28  0.029269  0.509715  0.505314  0.506358  0.513342
 2010-05-31  0.028934  0.513467  0.544155  0.521765  0.553366
 2010-06-01  0.043992  0.555985  0.577367  0.560822  0.570559
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.009419  0.224537  0.216049  0.225170  0.225317
 2022-07-20  0.019898  0.232880  0.219924  0.231045  0.225596
 2022-07-21  0.013165  0.226870  0.215533  0.225322  0.224796
 2022-07-22  0.028136  0.226870  0.220385  0.227444  0.227494
 2022-07-25  0.000000  0.226496  0.216640  0.230817  0.228574

 [3002 rows x 5 columns],
 'Transport':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.016983  0.657058  0.663144  0.675934  0.682304
 2010-05-27  0.011530  0.667786  0.666047  0.677479  0.690749
 2010-05-28  0.009056  0.692639  0.677649  0.697269  0.691349
 2010-05-31  0.007711  0.680974  0.679164  0.704394  0.703544
 2010-06-01  0.005484  0.693599  0.676949  0.698094  0.688967
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.043768  0.176949  0.163524  0.186694  0.183359
 2022-07-20  0.034799  0.185339  0.165689  0.190003  0.184072
 2022-07-21  0.027433  0.180586  0.166599  0.190326  0.185067
 2022-07-22  0.026129  0.182104  0.164401  0.190510  0.181764
 2022-07-25  0.007830  0.177953  0.164445  0.189046  0.184751

 [3002 rows x 5 columns],
 'Distribution':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.045889  0.540519  0.545231  0.546903  0.571360
 2010-05-27  0.039852  0.544756  0.531850  0.549554  0.545043
 2010-05-28  0.037190  0.543329  0.533906  0.552269  0.557287
 2010-05-31  0.023256  0.554800  0.557778  0.568242  0.584127
 2010-06-01  0.015078  0.570259  0.565432  0.585206  0.587203
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.023578  0.114598  0.101876  0.122284  0.115465
 2022-07-20  0.080795  0.118738  0.116752  0.123561  0.121920
 2022-07-21  0.060195  0.122361  0.120909  0.133551  0.132606
 2022-07-22  0.021053  0.129162  0.118794  0.137457  0.127857
 2022-07-25  0.007029  0.126871  0.116533  0.136330  0.129489

 [3002 rows x 5 columns],
 'Power':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.036361  0.101057  0.082538  0.097900  0.088997
 2010-05-27  0.032396  0.098235  0.081149  0.099345  0.094142
 2010-05-28  0.034695  0.106885  0.092833  0.108800  0.107440
 2010-05-31  0.038613  0.116340  0.099168  0.119085  0.112756
 2010-06-01  0.041749  0.120066  0.105531  0.123820  0.116427
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.023763  0.962363  0.934703  0.950406  0.937853
 2022-07-20  0.020738  0.943551  0.934245  0.944456  0.945423
 2022-07-21  0.013524  0.946134  0.936092  0.956128  0.956522
 2022-07-22  0.012155  0.959780  0.927521  0.958989  0.945423
 2022-07-25  0.000000  0.943791  0.921046  0.959704  0.953219

 [3002 rows x 5 columns],
 'Tele':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.187474  0.457867  0.452613  0.441872  0.435709
 2010-05-27  0.310803  0.442158  0.438710  0.442334  0.437309
 2010-05-28  0.184048  0.454655  0.440360  0.443720  0.433758
 2010-05-31  0.099397  0.434529  0.454364  0.448648  0.456114
 2010-06-01  0.150427  0.461531  0.463566  0.474003  0.473668
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.036961  0.840201  0.825806  0.839193  0.820805
 2022-07-20  0.072263  0.831016  0.818305  0.825489  0.811653
 2022-07-21  0.058580  0.805069  0.808302  0.811785  0.799150
 2022-07-22  0.031169  0.798394  0.789097  0.805831  0.784146
 2022-07-25  0.000000  0.792522  0.792448  0.814351  0.794149

 [3002 rows x 5 columns],
 'Finance':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.051981  0.356347  0.348200  0.339280  0.337673
 2010-05-27  0.054347  0.356284  0.331760  0.358147  0.354877
 2010-05-28  0.040012  0.388081  0.354126  0.392864  0.367386
 2010-05-31  0.015286  0.392191  0.351647  0.392256  0.362677
 2010-06-01  0.023037  0.377389  0.336705  0.380662  0.355490
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.010888  0.249080  0.207350  0.265056  0.232528
 2022-07-20  0.021083  0.266100  0.226839  0.271822  0.238476
 2022-07-21  0.013333  0.255762  0.213077  0.266931  0.237667
 2022-07-22  0.014411  0.256468  0.214774  0.257580  0.218885
 2022-07-25  0.003559  0.243734  0.191626  0.254590  0.215937

 [3002 rows x 5 columns],
 'Brokerage':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.069819  0.166657  0.145787  0.178372  0.169360
 2010-05-27  0.049902  0.151252  0.149202  0.177387  0.181615
 2010-05-28  0.045075  0.184230  0.158645  0.195769  0.180228
 2010-05-31  0.058789  0.168283  0.157351  0.193829  0.189313
 2010-06-01  0.050143  0.174902  0.162858  0.203190  0.189115
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.025001  0.276602  0.267208  0.312067  0.298616
 2022-07-20  0.055068  0.311748  0.307930  0.344398  0.320975
 2022-07-21  0.033439  0.309266  0.301790  0.347723  0.334928
 2022-07-22  0.020654  0.323358  0.305176  0.360440  0.336909
 2022-07-25  0.000000  0.321219  0.314565  0.360163  0.334277

 [3002 rows x 5 columns],
 'Insurer':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.520208  0.371803  0.407301  0.377312  0.440268
 2010-05-27  0.323024  0.417946  0.414704  0.428059  0.444744
 2010-05-28  0.194814  0.454476  0.421183  0.433640  0.436901
 2010-05-31  0.168627  0.429716  0.413059  0.435654  0.440228
 2010-06-01  0.188890  0.438050  0.411373  0.434909  0.422958
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.056930  0.496902  0.483805  0.504916  0.509328
 2022-07-20  0.072099  0.513889  0.498982  0.525303  0.519983
 2022-07-21  0.060910  0.509892  0.491784  0.516238  0.514042
 2022-07-22  0.045848  0.504157  0.488432  0.516499  0.504139
 2022-07-25  0.000000  0.497662  0.482530  0.513981  0.500911

 [3002 rows x 5 columns],
 'Service':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.107357  0.030957  0.038521  0.036364  0.042674
 2010-05-27  0.137669  0.041609  0.044487  0.046422  0.045038
 2010-05-28  0.173509  0.046906  0.043378  0.038979  0.043789
 2010-05-31  0.165630  0.043173  0.043413  0.045127  0.045404
 2010-06-01  0.107265  0.045095  0.041942  0.042248  0.042504
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.039242  0.401602  0.396024  0.405942  0.398865
 2022-07-20  0.080265  0.412789  0.416634  0.415193  0.409905
 2022-07-21  0.060092  0.412899  0.420659  0.420463  0.421880
 2022-07-22  0.062300  0.423200  0.420985  0.429490  0.418804
 2022-07-25  0.012936  0.418825  0.413806  0.419566  0.413146

 [3002 rows x 5 columns],
 'Manufacturer':                  거래량        시가        고가        저가        종가
 일자
 2010-05-26  0.204629  0.250611  0.241410  0.267889  0.277861
 2010-05-27  0.169068  0.257941  0.262432  0.277376  0.300590
 2010-05-28  0.142117  0.301924  0.277728  0.304470  0.300904
 2010-05-31  0.071018  0.293830  0.275166  0.315967  0.308533
 2010-06-01  0.151906  0.294059  0.273734  0.290642  0.279670
 ...              ...       ...       ...       ...       ...
 2022-07-19  0.032373  0.476275  0.464158  0.511545  0.506882
 2022-07-20  0.033646  0.508728  0.476085  0.525752  0.505828
 2022-07-21  0.059803  0.492059  0.479227  0.521997  0.515006
 2022-07-22  0.048691  0.500076  0.475588  0.525084  0.512387
 2022-07-25  0.015682  0.495235  0.486513  0.533655  0.530476

 [3002 rows x 5 columns]}

In [4]:
with open('df_sector.pickle','rb') as f:
    df_sector = pickle.load(f)

In [9]:
df_sector

{'Food': {'097950':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   3380  397000  397500  394000  395000
  1    2022-07-20  39486  402000  403000  395500  396500
  2    2022-07-19  41409  393000  405000  390000  405000
  3    2022-07-18  27816  396000  399000  389000  391000
  4    2022-07-15  40227  395000  401000  381000  397500
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01  31617  214000  215000  210000  211000
  2996 2010-05-31  30990  215000  215000  211500  214000
  2997 2010-05-28  64458  211500  213000  208000  213000
  2998 2010-05-27  46323  208500  212000  205000  211500
  2999 2010-05-26  77164  212500  213500  203500  213500

  [3000 rows x 6 columns],
  '271560':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21    16813  101500  103000  101500  102500
  1    2022-07-20   157611  106000  106500  101500  102000
  2    2022-07-19   119285  104000  106000  102500  105000
  3    2022-07-18   140201  106500  107000  103500  104000
  4    2022-07-15    90893  108500  108500  104000  106500
  ...         ...      ...     ...     ...     ...     ...
  1234 2017-07-13   218138   83400   84000   80800   81600
  1235 2017-07-12   238407   83700   84600   80000   83500
  1236 2017-07-11   422303   88000   88000   82700   82800
  1237 2017-07-10   840451   82300   88000   81000   88000
  1238 2017-07-07  1619864   87100   89700   75700   82300

  [1239 rows x 6 columns],
  '000080':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   35515  29700  29800  29600  29650
  1    2022-07-20  175862  30050  30250  29700  29800
  2    2022-07-19  127612  29650  30150  29400  29800
  3    2022-07-18  173327  29250  29750  29200  29600
  4    2022-07-15  210606  30000  30000  28950  29300
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01   89108  33050  33850  32950  33200
  2996 2010-05-31  103839  31700  33300  31700  33050
  2997 2010-05-28  117860  32400  32500  31400  31550
  2998 2010-05-27  262075  31400  34900  31150  32050
  2999 2010-05-26  123593  31300  31400  30550  31400

  [3000 rows x 6 columns],
  '004370':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   2347  277000  277500  276000  277000
  1    2022-07-20  30147  283500  284000  276500  277500
  2    2022-07-19  15218  279500  284000  277500  283000
  3    2022-07-18  14217  281500  282500  278000  279000
  4    2022-07-15  18808  283000  284000  277500  280500
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01   7402  226500  230000  226500  230000
  2996 2010-05-31   7356  232000  233000  225500  228000
  2997 2010-05-28   7628  227000  227000  224500  225500
  2998 2010-05-27   8793  227000  230000  225000  228000
  2999 2010-05-26  14811  223500  230500  222500  227500

  [3000 rows x 6 columns],
  '005300':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   2593  173500  174000  172500  173000
  1    2022-07-20  13612  174000  176500  172500  174000
  2    2022-07-19  29041  168500  173500  168000  173500
  3    2022-07-18  29958  170500  172000  167500  168500
  4    2022-07-15  24548  173500  173500  165000  171000
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01  15030   78700   79700   78600   78900
  2996 2010-05-31  23650   79300   80700   78600   78700
  2997 2010-05-28  20540   78600   81400   78200   78700
  2998 2010-05-27  18190   77100   79000   77000   78500
  2999 2010-05-26  22910   76200   79700   76200   78500

  [3000 rows x 6 columns]},
 'Clothing': {'383220':             일자      거래량      시가      고가      저가      종가
  0   2022-07-21    21028  140000  145000  140000  144000
  1   2022-07-20    86060  141500  144500  139000  140000
  2   2022-07-19    48976  138000  142500  138000  139500
  3   2022-07-18    61299  140500  142000  137000  139000
  4   2022-07-15   122342  136000  142000  133500  140500
  ..         ...      ...     ...     ...     ...     ...
  285 2021-05-27   349185   86000   87400   84400   87300
  286 2021-05-26   503055   86000   88600   81200   87300
  287 2021-05-25   514200   88600   89000   83200   86000
  288 2021-05-24   879900   83600   91000   81500   89000
  289 2021-05-21  2774180   72000   93600   72000   82500

  [290 rows x 6 columns],
  '093050':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21    8832  17450  17600  17050  17150
  1    2022-07-20   62227  16850  17500  16700  17400
  2    2022-07-19  102588  15700  16900  15550  16850
  3    2022-07-18   21894  15350  15750  15250  15700
  4    2022-07-15   41203  15350  15500  15050  15200
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  236384  26050  26200  25200  25350
  2996 2010-05-31  166055  25950  26350  25400  26350
  2997 2010-05-28  176589  25800  26200  25500  25700
  2998 2010-05-27  269920  26000  26000  25050  25700
  2999 2010-05-26   95745  26100  26400  25700  25750

  [3000 rows x 6 columns],
  '020000':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21    7160  29950  30400  29950  30350
  1    2022-07-20   62854  30200  30550  30000  30150
  2    2022-07-19   46879  29150  30050  29150  29900
  3    2022-07-18   58144  29200  29750  28850  29500
  4    2022-07-15   54818  29300  29300  28150  28550
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01   81101  14350  14350  14000  14050
  2996 2010-05-31   87060  14000  14450  14000  14300
  2997 2010-05-28  106458  14100  14150  13700  14100
  2998 2010-05-27  161885  14200  14500  13800  13950
  2999 2010-05-26   54425  14400  14550  14000  14400

  [3000 rows x 6 columns],
  '105630':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   81316  16700  17050  16500  16850
  1    2022-07-20  299231  16950  17400  16600  16700
  2    2022-07-19  227190  16050  16600  15950  16450
  3    2022-07-18  219515  15800  16150  15550  16000
  4    2022-07-15  197073  15850  16050  15400  15650
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  135918   6050   6117   5720   5757
  2996 2010-05-31   65822   6230   6230   6027   6110
  2997 2010-05-28  181957   6350   6350   6117   6147
  2998 2010-05-27  170703   6155   6380   5855   6350
  2999 2010-05-26  132346   5967   6298   5855   6230

  [3000 rows x 6 columns],
  '001070':              일자    거래량     시가     고가     저가     종가
  0    2022-07-21   5424  49600  50100  49600  50000
  1    2022-07-20  18173  49450  50000  49250  50000
  2    2022-07-19   1437  49150  49900  49050  49900
  3    2022-07-18   2318  48850  49600  48850  49450
  4    2022-07-15  45220  48750  49150  48000  49150
  ...         ...    ...    ...    ...    ...    ...
  2995 2010-06-01   2550   5280   5300   5120   5300
  2996 2010-05-31   2550   5060   5300   5060   5290
  2997 2010-05-28  11050   5290   5290   5060   5060
  2998 2010-05-27   6150   5180   5400   5100   5230
  2999 2010-05-26  14905   4970   5100   4810   5090

  [3000 rows x 6 columns]},
 'Chemical': {'051910':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21  123815  541000  558000  540000  555000
  1    2022-07-20  225805  538000  547000  535000  540000
  2    2022-07-19  161162  525000  530000  517000  521000
  3    2022-07-18  160879  514000  517000  505000  515000
  4    2022-07-15  229151  529000  530000  507000  512000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  218930  271500  274500  267000  272000
  2996 2010-05-31  247644  270000  277000  267000  273000
  2997 2010-05-28  412162  274500  276000  264000  270000
  2998 2010-05-27  305893  265000  275000  263500  272000
  2999 2010-05-26  423060  261500  271000  259500  268500

  [3000 rows x 6 columns],
  '096770':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21    37491  178000  179500  176500  178500
  1    2022-07-20   256533  179500  180000  176500  178500
  2    2022-07-19   371392  174000  178000  173000  177000
  3    2022-07-18   245629  173500  174000  170000  173000
  4    2022-07-15   329142  172500  174000  166500  170500
  ...         ...      ...     ...     ...     ...     ...
  2995 2010-06-01   557598  107500  108500  104500  108000
  2996 2010-05-31   686012  107500  111000  106500  108500
  2997 2010-05-28  1548069  105000  109000  103500  107500
  2998 2010-05-27   904128   97300  101500   96500  100500
  2999 2010-05-26   942247   99900   99900   94300   97100

  [3000 rows x 6 columns],
  '010950':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   60485  93600  94000  92800  93900
  1    2022-07-20  393638  94100  94400  92800  93700
  2    2022-07-19  371087  93300  94900  92400  93200
  3    2022-07-18  373881  89600  92300  88000  92300
  4    2022-07-15  232955  90700  90800  88300  88900
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  154475  51300  52500  51100  52000
  2996 2010-05-31  152228  50900  51800  50500  51700
  2997 2010-05-28  291916  50100  50900  49450  50900
  2998 2010-05-27  346735  49600  49700  49000  49150
  2999 2010-05-26  195898  50000  51100  49650  49650

  [3000 rows x 6 columns],
  '051900':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   6078  724000  727000  717000  721000
  1    2022-07-20  48112  720000  723000  710000  723000
  2    2022-07-19  33057  717000  718000  704000  710000
  3    2022-07-18  32283  713000  725000  712000  717000
  4    2022-07-15  38351  726000  727000  700000  711000
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01  24899  317500  331000  316000  325000
  2996 2010-05-31  25797  316000  323500  316000  319000
  2997 2010-05-28  45378  306000  317500  303000  316000
  2998 2010-05-27  43499  305000  309500  301000  306000
  2999 2010-05-26  23804  302000  309000  302000  305500

  [3000 rows x 6 columns],
  '090430':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21   53062  137000  137500  134500  136000
  1    2022-07-20  191796  136000  139000  134000  138000
  2    2022-07-19  103096  133000  135000  132500  133500
  3    2022-07-18  117689  134500  136500  133000  134000
  4    2022-07-15  127723  135000  136000  131000  133500
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01   72990   90800   93800   90600   93800
  2996 2010-05-31   86570   91100   92900   90600   91700
  2997 2010-05-28  149120   92400   92400   89500   91800
  2998 2010-05-27  139430   90200   92500   89100   91000
  2999 2010-05-26  132680   90000   91500   89000   91500

  [3000 rows x 6 columns]},
 'Medicine': {'207940':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21     7365  820000  826000  817000  818000
  1    2022-07-20    35555  823000  827000  817000  823000
  2    2022-07-19    46882  824000  828000  812000  819000
  3    2022-07-18    46011  813000  817000  803000  810000
  4    2022-07-15    38951  826000  828000  813000  817000
  ...         ...      ...     ...     ...     ...     ...
  1396 2016-11-16  1680639  166529  170976  161587  168011
  1397 2016-11-15  2623646  176906  179376  160599  164058
  1398 2016-11-14  3012422  163070  175423  163070  173447
  1399 2016-11-11  8236911  147751  184318  140339  159610
  1400 2016-11-10  7264007  133421  146268  124032  142315

  [1401 rows x 6 columns],
  '068270':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21    77587  183500  184000  180500  181000
  1    2022-07-20   242433  185000  186500  183000  184000
  2    2022-07-19   223541  184000  186500  182500  183500
  3    2022-07-18   366865  187500  187500  180000  183000
  4    2022-07-15   389861  189500  189500  183000  186500
  ...         ...      ...     ...     ...     ...     ...
  2995 2010-06-01   956074   18705   18972   18350   18572
  2996 2010-05-31  1050816   18661   18927   18305   18927
  2997 2010-05-28  2912063   18172   18838   18083   18572
  2998 2010-05-27  1340352   17150   17772   16928   17772
  2999 2010-05-26  1753427   17194   17461   16661   17417

  [3000 rows x 6 columns],
  '302440':             일자       거래량      시가      고가      저가      종가
  0   2022-07-21    163525  135000  135500  131000  131500
  1   2022-07-20    942995  134500  137500  132000  134000
  2   2022-07-19    967387  136000  138000  132000  132500
  3   2022-07-18   1449037  138000  138500  129500  134000
  4   2022-07-15   1902745  143500  145500  135500  137000
  ..         ...       ...     ...     ...     ...     ...
  329 2021-03-24   1707179  138000  142000  135500  136500
  330 2021-03-23   2980953  147000  149500  138000  140500
  331 2021-03-22   4675116  161000  162500  143000  144000
  332 2021-03-19  12468903  184000  190000  166000  166500
  333 2021-03-18    876189  130000  169000  130000  169000

  [334 rows x 6 columns],
  '000100':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   35204  57600  58100  57200  57400
  1    2022-07-20  127748  58600  58600  57500  57900
  2    2022-07-19   99577  57700  58600  57700  58100
  3    2022-07-18  100369  57400  58100  57300  57700
  4    2022-07-15  126581  57500  57800  56600  57300
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  129918  21477  21844  21256  21844
  2996 2010-05-31  254568  21109  21771  20962  21550
  2997 2010-05-28  268899  21182  21256  20815  21182
  2998 2010-05-27  308756  20741  21403  20520  21182
  2999 2010-05-26  581890  21477  21771  20668  20668

  [3000 rows x 6 columns],
  '128940':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21    6051  311500  314000  308500  308500
  1    2022-07-20   27469  314000  315500  309000  313000
  2    2022-07-19   37063  307500  314500  305000  310500
  3    2022-07-18   78290  312000  314000  298000  306000
  4    2022-07-15   32823  312000  318000  307000  314000
  ...         ...     ...     ...     ...     ...     ...
  2949 2010-08-05  114537   59552   59552   56268   56654
  2950 2010-08-04   99727   58715   60002   55367   58715
  2951 2010-08-03   57060   58715   59873   58586   58715
  2952 2010-08-02  159281   63414   63672   58264   58586
  2953 2010-07-30  383395   57942   66633   57942   64316

  [2954 rows x 6 columns]},
 'Non_Metal': {'003670':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21   74995  118500  120500  117000  118500
  1    2022-07-20  318270  116000  120000  115500  118000
  2    2022-07-19  188757  111500  115000  110500  113500
  3    2022-07-18  235294  110000  112500  107000  112000
  4    2022-07-15  156374  110500  110500  108000  109000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  138936    6956    7172    6862    7144
  2996 2010-05-31   74819    6956    6956    6721    6881
  2997 2010-05-28  125223    7323    7323    6834    6909
  2998 2010-05-27  100128    6918    7041    6909    6984
  2999 2010-05-26  248234    7041    7041    6853    6965

  [3000 rows x 6 columns],
  '003410':              일자     거래량    시가    고가    저가    종가
  0    2022-07-21   56260  6270  6320  6260  6310
  1    2022-07-20  572728  6350  6420  6260  6290
  2    2022-07-19  268789  6290  6340  6240  6300
  3    2022-07-18  327802  6220  6290  6210  6290
  4    2022-07-15  554727  6170  6230  6010  6210
  ...         ...     ...   ...   ...   ...   ...
  2995 2010-06-01  632132  1131  1162  1131  1151
  2996 2010-05-31  445630  1144  1172  1125  1146
  2997 2010-05-28  521564  1183  1183  1149  1159
  2998 2010-05-27  311749  1149  1175  1149  1162
  2999 2010-05-26  361744  1170  1201  1149  1181

  [3000 rows x 6 columns],
  '010780':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21    6723  40200  40300  39850  40200
  1    2022-07-20  162863  40150  40500  39750  40250
  2    2022-07-19   62032  39150  40350  39150  39800
  3    2022-07-18   61481  38450  39900  38200  39300
  4    2022-07-15   35393  39100  39500  37600  38100
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01   31363   5788   5942   5788   5852
  2996 2010-05-31   53638   5891   5910   5795   5827
  2997 2010-05-28   50016   6140   6191   5795   5852
  2998 2010-05-27  129096   5501   6076   5437   6076
  2999 2010-05-26   14484   5501   5501   5360   5424

  [3000 rows x 6 columns],
  '300720':             일자      거래량     시가     고가     저가     종가
  0   2022-07-21     9360  13450  13550  13300  13500
  1   2022-07-20    65133  13500  13650  13250  13400
  2   2022-07-19    27012  13050  13350  13050  13250
  3   2022-07-18    66894  13050  13300  12800  13250
  4   2022-07-15   122495  13150  13250  12400  12850
  ..         ...      ...    ...    ...    ...    ...
  971 2018-08-10   469820  12150  12300  11850  12150
  972 2018-08-09   413900  12150  12150  11500  11650
  973 2018-08-08   643900  12300  12600  11750  12150
  974 2018-08-07  1889920  12300  14250  11700  12150
  975 2018-08-06  2694870  14450  18400  11700  11900

  [976 rows x 6 columns]},
 'Metal': {'005490':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21   34249  230000  231000  228000  230500
  1    2022-07-20  199103  234000  234000  230500  232000
  2    2022-07-19  273542  226500  230500  225500  230000
  3    2022-07-18  273744  226000  227000  222000  226500
  4    2022-07-15  298831  225000  228000  221500  224000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  266996  468000  470000  457500  460000
  2996 2010-05-31  182932  471000  473500  465500  472000
  2997 2010-05-28  292027  474500  474500  465500  472000
  2998 2010-05-27  391049  457000  470000  454500  464500
  2999 2010-05-26  427735  455000  463500  451000  454500

  [3000 rows x 6 columns],
  '010130':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21    6169  456000  457500  453500  455000
  1    2022-07-20   39108  461000  461500  453000  457500
  2    2022-07-19   23273  458500  463000  455000  456500
  3    2022-07-18   36699  451000  460000  447500  460000
  4    2022-07-15   20009  454000  455000  445000  450000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01   67772  196500  196500  192500  195500
  2996 2010-05-31   39725  193500  197500  192000  197500
  2997 2010-05-28   97307  197500  198000  190500  193500
  2998 2010-05-27  112336  186000  194000  184000  193000
  2999 2010-05-26   89574  186500  191000  184500  186000

  [3000 rows x 6 columns],
  '004020':              일자      거래량     시가     고가     저가     종가
  0    2022-07-21    69524  32700  33100  32600  33100
  1    2022-07-20   415165  33150  33300  32750  33050
  2    2022-07-19   342684  32000  32750  31900  32600
  3    2022-07-18   382662  31700  32150  31350  32100
  4    2022-07-15   344704  31900  32000  30650  31400
  ...         ...      ...    ...    ...    ...    ...
  2995 2010-06-01   318099  88100  88500  86700  87500
  2996 2010-05-31   335238  87100  88300  87100  88200
  2997 2010-05-28   746510  88200  89300  87500  87900
  2998 2010-05-27   870363  84200  88500  84000  87000
  2999 2010-05-26  1043037  82800  85500  82600  85500

  [3000 rows x 6 columns],
  '016380':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21  101890   12750   12750   12550   12650
  1    2022-07-20  574238   12900   13050   12600   12750
  2    2022-07-19  476257   12500   12750   12350   12550
  3    2022-07-18  499316   12400   12600   12300   12500
  4    2022-07-15  698279   12650   12700   12000   12200
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01    3735  502670  502670  489863  492531
  2996 2010-05-31    3643  490930  503204  485594  496800
  2997 2010-05-28    5994  498935  507473  491464  496267
  2998 2010-05-27    6400  477056  492531  474922  487729

In [8]:
df_sector.keys()

dict_keys(['Food', 'Clothing', 'Chemical', 'Medicine', 'Non_Metal', 'Metal', 'Machine', 'Electronic', 'Construction', 'Transport', 'Distribution', 'Power', 'Tele', 'Finance', 'Brokerage', 'Insurer', 'Service', 'Manufacturer'])

In [12]:
df_scaled_UTD['Food'].head(11)

                 거래량        시가        고가        저가        종가
일자
2010-05-26  0.042257  0.056702  0.043803  0.081957  0.085369
2010-05-27  0.063952  0.057396  0.044945  0.089734  0.084190
2010-05-28  0.035991  0.065028  0.042088  0.095426  0.082391
2010-05-31  0.025994  0.076824  0.053660  0.102915  0.089309
2010-06-01  0.020917  0.068842  0.048728  0.103992  0.088413
2010-06-03  0.037942  0.081820  0.059661  0.107305  0.096642
2010-06-04  0.017639  0.079527  0.053232  0.102984  0.085369
2010-06-07  0.019867  0.058506  0.039659  0.096290  0.079624
2010-06-08  0.016428  0.063569  0.038871  0.090887  0.075545
2010-06-09  0.016177  0.058573  0.038659  0.093047  0.078727
2010-06-10  0.026297  0.061487  0.047088  0.097730  0.088274

In [13]:
with open ('history_dic.pickle','rb') as f:
    history_dic = pickle.load(f)

ModuleNotFoundError: No module named 'keras.saving'

In [ ]:
for sector_name, hist in history_dic.items():
    plt.plot(hist.history['loss'])
    plt.plot(hist.history['val_loss'])
    plt.title('Loss')
    plt.legend(['train','test'], loc='upper left')
    plt.show()