In [2]:
import pickle
import numpy as np
import pandas as pd

In [3]:
with open('df_scaled.pickle','rb') as f:
    df_scaled = pickle.load(f)

In [4]:
df_scaled['Food']

                  종가       등락률     거래변동량  코스피지수_증감량
일자
2010-05-14  0.074920  0.491660  0.000000   0.511587
2010-05-17  0.077067  0.468725  0.025468   0.342590
2010-05-18  0.101557  0.554667  0.041343   0.479910
2010-05-19  0.087859  0.434181  0.027336   0.461179
2010-05-20  0.089447  0.486699  0.028428   0.397058
...              ...       ...       ...        ...
2022-07-06  0.417075  0.499675  0.023779   0.320948
2022-07-07  0.417794  0.515987  0.040026   0.673459
2022-07-08  0.410821  0.472507  0.022978   0.574176
2022-07-11  0.406615  0.454828  0.016001   0.471981
2022-07-12  0.415415  0.495849  0.027874   0.425365

[3000 rows x 4 columns]

In [26]:
pd.DataFrame(result['Food']['정규화_종가'])

            정규화_종가
일자
2010-05-12  0.2250
2010-05-13  0.2258
2010-05-14  0.2101
2010-05-17  0.2037
2010-05-18  0.2076
...            ...
2022-07-04  0.4641
2022-07-05  0.4554
2022-07-06  0.4559
2022-07-07  0.4624
2022-07-08  0.4574

[3000 rows x 1 columns]

# 추가 전처리

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_sector = {}
#스케일을 적용할 column을 정의합니다.
scale_cols = ['등락률','거래변동량', '코스피지수_증감량']
for sector_name, df in result.items():
    scaled=scaler.fit(df[scale_cols])
    scaled_df = pd.DataFrame(scaled)
    scaled_sector[sector_name] = pd.merge(scaled,pd.DataFrame(df['정규화_종가']),on=id,how='inner')

TypeError: Can only merge Series or DataFrame objects, a <class 'sklearn.preprocessing._data.MinMaxScaler'> was passed

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('Close', 1), df['Close'], test_size=0.2, random_state=0, shuffle=False)