# 1. 환경설정

In [1]:
import pickle
import time
import pandas as pd
import pickle
from pykiwoom.kiwoom import *
import warnings
warnings.filterwarnings('ignore')
kiwoom = Kiwoom()
kiwoom.CommConnect(block=True)

In [2]:
state = kiwoom.GetConnectState()
if state == 0:
    print("미연결")
elif state == 1:
    print("연결완료")

연결완료

# 2. 데이터 읽기

In [4]:
with open('sector.pickle','rb') as f:
    sector = pickle.load(f)
with open('df_sector.pickle','rb') as f:
    df_sector = pickle.load(f)
#with open('kospi.pickle','rb') as f:
 #   kospi = pickle.load(f)

In [5]:
sector

{'Food': ['097950', '271560', '000080', '004370', '005300'],
 'Clothing': ['383220', '093050', '020000', '105630', '001070'],
 'Chemical': ['051910', '096770', '010950', '051900', '090430'],
 'Medicine': ['207940', '068270', '302440', '000100', '128940'],
 'Non_Metal': ['003670', '003410', '010780', '300720'],
 'Metal': ['005490', '010130', '004020', '016380', '001230'],
 'Machine': ['034020', '018880', '241560', '112610'],
 'Electronic': ['005930', '000660', '373220', '006400', '066570'],
 'Construction': ['000720', '006360', '047040', '051600'],
 'Transport': ['011200', '003490', '086280', '180640', '028670'],
 'Distribution': ['028260', '023530', '282330', '139480', '004170'],
 'Power': ['015760', '036460', '017390'],
 'Tele': ['017670', '030200', '032640'],
 'Finance': ['323410', '003550', '000810', '377300', '006800'],
 'Brokerage': ['005940', '016360', '008560', '039490'],
 'Insurer': ['032830', '005830', '000060', '001450'],
 'Service': ['035420', '035720', '259960', '018260', '036570'],
 'Manufacturer': ['005380', '000270', '012330', '329180', '033780', '009150']}

In [6]:
df_sector

{'Food': {'097950':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   3380  397000  397500  394000  395000
  1    2022-07-20  39486  402000  403000  395500  396500
  2    2022-07-19  41409  393000  405000  390000  405000
  3    2022-07-18  27816  396000  399000  389000  391000
  4    2022-07-15  40227  395000  401000  381000  397500
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01  31617  214000  215000  210000  211000
  2996 2010-05-31  30990  215000  215000  211500  214000
  2997 2010-05-28  64458  211500  213000  208000  213000
  2998 2010-05-27  46323  208500  212000  205000  211500
  2999 2010-05-26  77164  212500  213500  203500  213500

  [3000 rows x 6 columns],
  '271560':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21    16813  101500  103000  101500  102500
  1    2022-07-20   157611  106000  106500  101500  102000
  2    2022-07-19   119285  104000  106000  102500  105000
  3    2022-07-18   140201  106500  107000  103500  104000
  4    2022-07-15    90893  108500  108500  104000  106500
  ...         ...      ...     ...     ...     ...     ...
  1234 2017-07-13   218138   83400   84000   80800   81600
  1235 2017-07-12   238407   83700   84600   80000   83500
  1236 2017-07-11   422303   88000   88000   82700   82800
  1237 2017-07-10   840451   82300   88000   81000   88000
  1238 2017-07-07  1619864   87100   89700   75700   82300

  [1239 rows x 6 columns],
  '000080':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   35515  29700  29800  29600  29650
  1    2022-07-20  175862  30050  30250  29700  29800
  2    2022-07-19  127612  29650  30150  29400  29800
  3    2022-07-18  173327  29250  29750  29200  29600
  4    2022-07-15  210606  30000  30000  28950  29300
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01   89108  33050  33850  32950  33200
  2996 2010-05-31  103839  31700  33300  31700  33050
  2997 2010-05-28  117860  32400  32500  31400  31550
  2998 2010-05-27  262075  31400  34900  31150  32050
  2999 2010-05-26  123593  31300  31400  30550  31400

  [3000 rows x 6 columns],
  '004370':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   2347  277000  277500  276000  277000
  1    2022-07-20  30147  283500  284000  276500  277500
  2    2022-07-19  15218  279500  284000  277500  283000
  3    2022-07-18  14217  281500  282500  278000  279000
  4    2022-07-15  18808  283000  284000  277500  280500
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01   7402  226500  230000  226500  230000
  2996 2010-05-31   7356  232000  233000  225500  228000
  2997 2010-05-28   7628  227000  227000  224500  225500
  2998 2010-05-27   8793  227000  230000  225000  228000
  2999 2010-05-26  14811  223500  230500  222500  227500

  [3000 rows x 6 columns],
  '005300':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   2593  173500  174000  172500  173000
  1    2022-07-20  13612  174000  176500  172500  174000
  2    2022-07-19  29041  168500  173500  168000  173500
  3    2022-07-18  29958  170500  172000  167500  168500
  4    2022-07-15  24548  173500  173500  165000  171000
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01  15030   78700   79700   78600   78900
  2996 2010-05-31  23650   79300   80700   78600   78700
  2997 2010-05-28  20540   78600   81400   78200   78700
  2998 2010-05-27  18190   77100   79000   77000   78500
  2999 2010-05-26  22910   76200   79700   76200   78500

  [3000 rows x 6 columns]},
 'Clothing': {'383220':             일자      거래량      시가      고가      저가      종가
  0   2022-07-21    21028  140000  145000  140000  144000
  1   2022-07-20    86060  141500  144500  139000  140000
  2   2022-07-19    48976  138000  142500  138000  139500
  3   2022-07-18    61299  140500  142000  137000  139000
  4   2022-07-15   122342  136000  142000  133500  140500
  ..         ...      ...     ...     ...     ...     ...
  285 2021-05-27   349185   86000   87400   84400   87300
  286 2021-05-26   503055   86000   88600   81200   87300
  287 2021-05-25   514200   88600   89000   83200   86000
  288 2021-05-24   879900   83600   91000   81500   89000
  289 2021-05-21  2774180   72000   93600   72000   82500

  [290 rows x 6 columns],
  '093050':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21    8832  17450  17600  17050  17150
  1    2022-07-20   62227  16850  17500  16700  17400
  2    2022-07-19  102588  15700  16900  15550  16850
  3    2022-07-18   21894  15350  15750  15250  15700
  4    2022-07-15   41203  15350  15500  15050  15200
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  236384  26050  26200  25200  25350
  2996 2010-05-31  166055  25950  26350  25400  26350
  2997 2010-05-28  176589  25800  26200  25500  25700
  2998 2010-05-27  269920  26000  26000  25050  25700
  2999 2010-05-26   95745  26100  26400  25700  25750

  [3000 rows x 6 columns],
  '020000':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21    7160  29950  30400  29950  30350
  1    2022-07-20   62854  30200  30550  30000  30150
  2    2022-07-19   46879  29150  30050  29150  29900
  3    2022-07-18   58144  29200  29750  28850  29500
  4    2022-07-15   54818  29300  29300  28150  28550
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01   81101  14350  14350  14000  14050
  2996 2010-05-31   87060  14000  14450  14000  14300
  2997 2010-05-28  106458  14100  14150  13700  14100
  2998 2010-05-27  161885  14200  14500  13800  13950
  2999 2010-05-26   54425  14400  14550  14000  14400

  [3000 rows x 6 columns],
  '105630':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   81316  16700  17050  16500  16850
  1    2022-07-20  299231  16950  17400  16600  16700
  2    2022-07-19  227190  16050  16600  15950  16450
  3    2022-07-18  219515  15800  16150  15550  16000
  4    2022-07-15  197073  15850  16050  15400  15650
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  135918   6050   6117   5720   5757
  2996 2010-05-31   65822   6230   6230   6027   6110
  2997 2010-05-28  181957   6350   6350   6117   6147
  2998 2010-05-27  170703   6155   6380   5855   6350
  2999 2010-05-26  132346   5967   6298   5855   6230

  [3000 rows x 6 columns],
  '001070':              일자    거래량     시가     고가     저가     종가
  0    2022-07-21   5424  49600  50100  49600  50000
  1    2022-07-20  18173  49450  50000  49250  50000
  2    2022-07-19   1437  49150  49900  49050  49900
  3    2022-07-18   2318  48850  49600  48850  49450
  4    2022-07-15  45220  48750  49150  48000  49150
  ...         ...    ...    ...    ...    ...    ...
  2995 2010-06-01   2550   5280   5300   5120   5300
  2996 2010-05-31   2550   5060   5300   5060   5290
  2997 2010-05-28  11050   5290   5290   5060   5060
  2998 2010-05-27   6150   5180   5400   5100   5230
  2999 2010-05-26  14905   4970   5100   4810   5090

  [3000 rows x 6 columns]},
 'Chemical': {'051910':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21  123815  541000  558000  540000  555000
  1    2022-07-20  225805  538000  547000  535000  540000
  2    2022-07-19  161162  525000  530000  517000  521000
  3    2022-07-18  160879  514000  517000  505000  515000
  4    2022-07-15  229151  529000  530000  507000  512000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  218930  271500  274500  267000  272000
  2996 2010-05-31  247644  270000  277000  267000  273000
  2997 2010-05-28  412162  274500  276000  264000  270000
  2998 2010-05-27  305893  265000  275000  263500  272000
  2999 2010-05-26  423060  261500  271000  259500  268500

  [3000 rows x 6 columns],
  '096770':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21    37491  178000  179500  176500  178500
  1    2022-07-20   256533  179500  180000  176500  178500
  2    2022-07-19   371392  174000  178000  173000  177000
  3    2022-07-18   245629  173500  174000  170000  173000
  4    2022-07-15   329142  172500  174000  166500  170500
  ...         ...      ...     ...     ...     ...     ...
  2995 2010-06-01   557598  107500  108500  104500  108000
  2996 2010-05-31   686012  107500  111000  106500  108500
  2997 2010-05-28  1548069  105000  109000  103500  107500
  2998 2010-05-27   904128   97300  101500   96500  100500
  2999 2010-05-26   942247   99900   99900   94300   97100

  [3000 rows x 6 columns],
  '010950':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   60485  93600  94000  92800  93900
  1    2022-07-20  393638  94100  94400  92800  93700
  2    2022-07-19  371087  93300  94900  92400  93200
  3    2022-07-18  373881  89600  92300  88000  92300
  4    2022-07-15  232955  90700  90800  88300  88900
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  154475  51300  52500  51100  52000
  2996 2010-05-31  152228  50900  51800  50500  51700
  2997 2010-05-28  291916  50100  50900  49450  50900
  2998 2010-05-27  346735  49600  49700  49000  49150
  2999 2010-05-26  195898  50000  51100  49650  49650

  [3000 rows x 6 columns],
  '051900':              일자    거래량      시가      고가      저가      종가
  0    2022-07-21   6078  724000  727000  717000  721000
  1    2022-07-20  48112  720000  723000  710000  723000
  2    2022-07-19  33057  717000  718000  704000  710000
  3    2022-07-18  32283  713000  725000  712000  717000
  4    2022-07-15  38351  726000  727000  700000  711000
  ...         ...    ...     ...     ...     ...     ...
  2995 2010-06-01  24899  317500  331000  316000  325000
  2996 2010-05-31  25797  316000  323500  316000  319000
  2997 2010-05-28  45378  306000  317500  303000  316000
  2998 2010-05-27  43499  305000  309500  301000  306000
  2999 2010-05-26  23804  302000  309000  302000  305500

  [3000 rows x 6 columns],
  '090430':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21   53062  137000  137500  134500  136000
  1    2022-07-20  191796  136000  139000  134000  138000
  2    2022-07-19  103096  133000  135000  132500  133500
  3    2022-07-18  117689  134500  136500  133000  134000
  4    2022-07-15  127723  135000  136000  131000  133500
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01   72990   90800   93800   90600   93800
  2996 2010-05-31   86570   91100   92900   90600   91700
  2997 2010-05-28  149120   92400   92400   89500   91800
  2998 2010-05-27  139430   90200   92500   89100   91000
  2999 2010-05-26  132680   90000   91500   89000   91500

  [3000 rows x 6 columns]},
 'Medicine': {'207940':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21     7365  820000  826000  817000  818000
  1    2022-07-20    35555  823000  827000  817000  823000
  2    2022-07-19    46882  824000  828000  812000  819000
  3    2022-07-18    46011  813000  817000  803000  810000
  4    2022-07-15    38951  826000  828000  813000  817000
  ...         ...      ...     ...     ...     ...     ...
  1396 2016-11-16  1680639  166529  170976  161587  168011
  1397 2016-11-15  2623646  176906  179376  160599  164058
  1398 2016-11-14  3012422  163070  175423  163070  173447
  1399 2016-11-11  8236911  147751  184318  140339  159610
  1400 2016-11-10  7264007  133421  146268  124032  142315

  [1401 rows x 6 columns],
  '068270':              일자      거래량      시가      고가      저가      종가
  0    2022-07-21    77587  183500  184000  180500  181000
  1    2022-07-20   242433  185000  186500  183000  184000
  2    2022-07-19   223541  184000  186500  182500  183500
  3    2022-07-18   366865  187500  187500  180000  183000
  4    2022-07-15   389861  189500  189500  183000  186500
  ...         ...      ...     ...     ...     ...     ...
  2995 2010-06-01   956074   18705   18972   18350   18572
  2996 2010-05-31  1050816   18661   18927   18305   18927
  2997 2010-05-28  2912063   18172   18838   18083   18572
  2998 2010-05-27  1340352   17150   17772   16928   17772
  2999 2010-05-26  1753427   17194   17461   16661   17417

  [3000 rows x 6 columns],
  '302440':             일자       거래량      시가      고가      저가      종가
  0   2022-07-21    163525  135000  135500  131000  131500
  1   2022-07-20    942995  134500  137500  132000  134000
  2   2022-07-19    967387  136000  138000  132000  132500
  3   2022-07-18   1449037  138000  138500  129500  134000
  4   2022-07-15   1902745  143500  145500  135500  137000
  ..         ...       ...     ...     ...     ...     ...
  329 2021-03-24   1707179  138000  142000  135500  136500
  330 2021-03-23   2980953  147000  149500  138000  140500
  331 2021-03-22   4675116  161000  162500  143000  144000
  332 2021-03-19  12468903  184000  190000  166000  166500
  333 2021-03-18    876189  130000  169000  130000  169000

  [334 rows x 6 columns],
  '000100':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21   35204  57600  58100  57200  57400
  1    2022-07-20  127748  58600  58600  57500  57900
  2    2022-07-19   99577  57700  58600  57700  58100
  3    2022-07-18  100369  57400  58100  57300  57700
  4    2022-07-15  126581  57500  57800  56600  57300
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01  129918  21477  21844  21256  21844
  2996 2010-05-31  254568  21109  21771  20962  21550
  2997 2010-05-28  268899  21182  21256  20815  21182
  2998 2010-05-27  308756  20741  21403  20520  21182
  2999 2010-05-26  581890  21477  21771  20668  20668

  [3000 rows x 6 columns],
  '128940':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21    6051  311500  314000  308500  308500
  1    2022-07-20   27469  314000  315500  309000  313000
  2    2022-07-19   37063  307500  314500  305000  310500
  3    2022-07-18   78290  312000  314000  298000  306000
  4    2022-07-15   32823  312000  318000  307000  314000
  ...         ...     ...     ...     ...     ...     ...
  2949 2010-08-05  114537   59552   59552   56268   56654
  2950 2010-08-04   99727   58715   60002   55367   58715
  2951 2010-08-03   57060   58715   59873   58586   58715
  2952 2010-08-02  159281   63414   63672   58264   58586
  2953 2010-07-30  383395   57942   66633   57942   64316

  [2954 rows x 6 columns]},
 'Non_Metal': {'003670':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21   74995  118500  120500  117000  118500
  1    2022-07-20  318270  116000  120000  115500  118000
  2    2022-07-19  188757  111500  115000  110500  113500
  3    2022-07-18  235294  110000  112500  107000  112000
  4    2022-07-15  156374  110500  110500  108000  109000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  138936    6956    7172    6862    7144
  2996 2010-05-31   74819    6956    6956    6721    6881
  2997 2010-05-28  125223    7323    7323    6834    6909
  2998 2010-05-27  100128    6918    7041    6909    6984
  2999 2010-05-26  248234    7041    7041    6853    6965

  [3000 rows x 6 columns],
  '003410':              일자     거래량    시가    고가    저가    종가
  0    2022-07-21   56260  6270  6320  6260  6310
  1    2022-07-20  572728  6350  6420  6260  6290
  2    2022-07-19  268789  6290  6340  6240  6300
  3    2022-07-18  327802  6220  6290  6210  6290
  4    2022-07-15  554727  6170  6230  6010  6210
  ...         ...     ...   ...   ...   ...   ...
  2995 2010-06-01  632132  1131  1162  1131  1151
  2996 2010-05-31  445630  1144  1172  1125  1146
  2997 2010-05-28  521564  1183  1183  1149  1159
  2998 2010-05-27  311749  1149  1175  1149  1162
  2999 2010-05-26  361744  1170  1201  1149  1181

  [3000 rows x 6 columns],
  '010780':              일자     거래량     시가     고가     저가     종가
  0    2022-07-21    6723  40200  40300  39850  40200
  1    2022-07-20  162863  40150  40500  39750  40250
  2    2022-07-19   62032  39150  40350  39150  39800
  3    2022-07-18   61481  38450  39900  38200  39300
  4    2022-07-15   35393  39100  39500  37600  38100
  ...         ...     ...    ...    ...    ...    ...
  2995 2010-06-01   31363   5788   5942   5788   5852
  2996 2010-05-31   53638   5891   5910   5795   5827
  2997 2010-05-28   50016   6140   6191   5795   5852
  2998 2010-05-27  129096   5501   6076   5437   6076
  2999 2010-05-26   14484   5501   5501   5360   5424

  [3000 rows x 6 columns],
  '300720':             일자      거래량     시가     고가     저가     종가
  0   2022-07-21     9360  13450  13550  13300  13500
  1   2022-07-20    65133  13500  13650  13250  13400
  2   2022-07-19    27012  13050  13350  13050  13250
  3   2022-07-18    66894  13050  13300  12800  13250
  4   2022-07-15   122495  13150  13250  12400  12850
  ..         ...      ...    ...    ...    ...    ...
  971 2018-08-10   469820  12150  12300  11850  12150
  972 2018-08-09   413900  12150  12150  11500  11650
  973 2018-08-08   643900  12300  12600  11750  12150
  974 2018-08-07  1889920  12300  14250  11700  12150
  975 2018-08-06  2694870  14450  18400  11700  11900

  [976 rows x 6 columns]},
 'Metal': {'005490':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21   34249  230000  231000  228000  230500
  1    2022-07-20  199103  234000  234000  230500  232000
  2    2022-07-19  273542  226500  230500  225500  230000
  3    2022-07-18  273744  226000  227000  222000  226500
  4    2022-07-15  298831  225000  228000  221500  224000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  266996  468000  470000  457500  460000
  2996 2010-05-31  182932  471000  473500  465500  472000
  2997 2010-05-28  292027  474500  474500  465500  472000
  2998 2010-05-27  391049  457000  470000  454500  464500
  2999 2010-05-26  427735  455000  463500  451000  454500

  [3000 rows x 6 columns],
  '010130':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21    6169  456000  457500  453500  455000
  1    2022-07-20   39108  461000  461500  453000  457500
  2    2022-07-19   23273  458500  463000  455000  456500
  3    2022-07-18   36699  451000  460000  447500  460000
  4    2022-07-15   20009  454000  455000  445000  450000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01   67772  196500  196500  192500  195500
  2996 2010-05-31   39725  193500  197500  192000  197500
  2997 2010-05-28   97307  197500  198000  190500  193500
  2998 2010-05-27  112336  186000  194000  184000  193000
  2999 2010-05-26   89574  186500  191000  184500  186000

  [3000 rows x 6 columns],
  '004020':              일자      거래량     시가     고가     저가     종가
  0    2022-07-21    69524  32700  33100  32600  33100
  1    2022-07-20   415165  33150  33300  32750  33050
  2    2022-07-19   342684  32000  32750  31900  32600
  3    2022-07-18   382662  31700  32150  31350  32100
  4    2022-07-15   344704  31900  32000  30650  31400
  ...         ...      ...    ...    ...    ...    ...
  2995 2010-06-01   318099  88100  88500  86700  87500
  2996 2010-05-31   335238  87100  88300  87100  88200
  2997 2010-05-28   746510  88200  89300  87500  87900
  2998 2010-05-27   870363  84200  88500  84000  87000
  2999 2010-05-26  1043037  82800  85500  82600  85500

  [3000 rows x 6 columns],
  '016380':              일자     거래량      시가      고가      저가      종가
  0    2022-07-21  101890   12750   12750   12550   12650
  1    2022-07-20  574238   12900   13050   12600   12750
  2    2022-07-19  476257   12500   12750   12350   12550
  3    2022-07-18  499316   12400   12600   12300   12500
  4    2022-07-15  698279   12650   12700   12000   12200
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01    3735  502670  502670  489863  492531
  2996 2010-05-31    3643  490930  503204  485594  496800
  2997 2010-05-28    5994  498935  507473  491464  496267
  2998 2010-05-27    6400  477056  492531  474922  487729

In [ ]:
#kospi

# 3. 데이터셋 최신화
1. 최신 주가 데이터 읽고 업종 데이터셋 추가
2. 최신 코스피 지수 읽고 코스피 데이터셋 추가

In [7]:
from datetime import date,datetime
today = date.today()
today = today.isoformat()
today = today.replace('-','')
#yesterday = int(today)-1
#yesterday = str(yesterday)
#print(yesterday, type(yesterday))
set_d = today

In [8]:
today

'20220721'

In [9]:
set_d

'20220721'

# 최신 data 수집

In [10]:
df_sector_2 = {'Food':{},
          'Clothing' : {},
          'Chemical' : {},
          'Medicine' : {},
          'Non_Metal' : {},
          'Metal': {},
          'Machine' : {},
          'Electronic' : {},
          'Construction' : {},
          'Transport': {},
          'Distribution' : {},
          'Power': {},
          'Tele' : {},
          'Finance': {},
          'Brokerage' : {},
          'Insurer': {},
          'Service': {},
          'Manufacturer': {}}

In [11]:
def Add_Data(sector_name,stockcode):
    df = kiwoom.block_request("opt10081",
                          종목코드=stockcode,
                          기준일자=set_d,
                          수정주가구분=1,
                          output="주식일봉차트조회",
                          next=0)
    df = df[['일자','현재가','거래량','시가','고가','저가']]
    df2 = pd.DataFrame()
    df2['일자'] = pd.to_datetime(df['일자'])
    df2['종가'] = df['현재가'].astype(int)
    df2['거래량'] = df['거래량'].astype(int)
    df2['시가'] = df['시가'].astype(int)
    df2['고가'] = df['고가'].astype(int)
    df2['저가'] = df['저가'].astype(int)
    df_sector_2[sector_name][stockcode] = df2
    del df2

In [12]:
import time

In [13]:
#데이터 수집 자동화 코드
for sector_name, stockcode_list in sector.items():
    print(f'---------{sector_name}업종 데이터 수집----------')
    for stockcode in stockcode_list:
        # 주식항목이름
        stockname = kiwoom.GetMasterCodeName(stockcode)
        print(f'--------[{stockname}] 항목 데이터 수집---------')
        Add_Data(sector_name,stockcode)
        time.sleep(0.2) #time을 안넣어주면 중간에 종종 수집이 안되고 멈추는 경우가 발생

---------Food업종 데이터 수집----------
--------[CJ제일제당] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[오리온] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[하이트진로] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[농심] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[롯데칠성] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Clothing업종 데이터 수집----------
--------[F&F] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[LF] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한섬] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한세실업] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

--------[대한방직] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Chemical업종 데이터 수집----------
--------[LG화학] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[SK이노베이션] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[S-Oil] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[LG생활건강] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

--------[아모레퍼시픽] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Medicine업종 데이터 수집----------
--------[삼성바이오로직스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[셀트리온] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[SK바이오사이언스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[유한양행] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한미약품] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Non_Metal업종 데이터 수집----------
--------[포스코케미칼] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[쌍용C&E] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[아이에스동서] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한일시멘트] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Metal업종 데이터 수집----------
--------[POSCO홀딩스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[고려아연] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[현대제철] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[KG스틸] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[동국제강] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Machine업종 데이터 수집----------
--------[두산에너빌리티] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한온시스템] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[두산밥캣] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[씨에스윈드] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Electronic업종 데이터 수집----------
--------[삼성전자] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[SK하이닉스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

--------[LG에너지솔루션] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[삼성SDI] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

--------[LG전자] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

---------Construction업종 데이터 수집----------
--------[현대건설] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[GS건설] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[대우건설] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한전KPS] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

---------Transport업종 데이터 수집----------
--------[HMM] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[대한항공] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[현대글로비스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한진칼] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[팬오션] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Distribution업종 데이터 수집----------
--------[삼성물산] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

--------[롯데쇼핑] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[BGF리테일] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

--------[이마트] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[신세계] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

---------Power업종 데이터 수집----------
--------[한국전력] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[한국가스공사] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[서울가스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Tele업종 데이터 수집----------
--------[SK텔레콤] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[KT] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

--------[LG유플러스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Finance업종 데이터 수집----------
--------[카카오뱅크] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[LG] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[삼성화재] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[카카오페이] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[미래에셋증권] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Brokerage업종 데이터 수집----------
--------[NH투자증권] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[삼성증권] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[메리츠증권] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[키움증권] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Insurer업종 데이터 수집----------
--------[삼성생명] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[DB손해보험] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[메리츠화재] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[현대해상] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Service업종 데이터 수집----------
--------[NAVER] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[카카오] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[크래프톤] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[삼성에스디에스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[엔씨소프트] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
---------Manufacturer업종 데이터 수집----------
--------[현대차] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

--------[기아] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[현대모비스] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[현대중공업] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[KT&G] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101
--------[삼성전기] 항목 데이터 수집---------
CommRqData opt10081 opt10081 0 0101

In [14]:
df_sector_2

{'Food': {'097950':             일자      종가    거래량      시가      고가      저가
  0   2022-07-21  395500   4227  397000  397500  394000
  1   2022-07-20  396500  39486  402000  403000  395500
  2   2022-07-19  405000  41409  393000  405000  390000
  3   2022-07-18  391000  27816  396000  399000  389000
  4   2022-07-15  397500  40227  395000  401000  381000
  ..         ...     ...    ...     ...     ...     ...
  595 2020-02-25  262000  49084  263000  267500  260500
  596 2020-02-24  263000  89274  272500  279500  260000
  597 2020-02-21  267500  40858  268500  275000  267500
  598 2020-02-20  273500  37609  274000  274500  269000
  599 2020-02-19  274500  64463  272500  278000  272000

  [600 rows x 6 columns],
  '271560':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  101500   26597  101500  103000  101500
  1   2022-07-20  102000  157611  106000  106500  101500
  2   2022-07-19  105000  119285  104000  106000  102500
  3   2022-07-18  104000  140201  106500  107000  103500
  4   2022-07-15  106500   90893  108500  108500  104000
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  101000  126265   99900  102500   98000
  596 2020-02-24   96900  122362  100500  101000   96200
  597 2020-02-21  103500   63674  102000  104500  102000
  598 2020-02-20  102500  161730  107000  107500  102000
  599 2020-02-19  108000   41823  107500  109500  106500

  [600 rows x 6 columns],
  '000080':             일자     종가      거래량     시가     고가     저가
  0   2022-07-21  29650    43306  29700  29800  29600
  1   2022-07-20  29800   175862  30050  30250  29700
  2   2022-07-19  29800   127612  29650  30150  29400
  3   2022-07-18  29600   173327  29250  29750  29200
  4   2022-07-15  29300   210606  30000  30000  28950
  ..         ...    ...      ...    ...    ...    ...
  595 2020-02-25  28650   492418  28000  28950  27000
  596 2020-02-24  28300  1048672  29300  29500  27900
  597 2020-02-21  30000   639772  30800  31200  29900
  598 2020-02-20  31250   955674  31550  32750  31000
  599 2020-02-19  31500  1005051  29300  31750  29250

  [600 rows x 6 columns],
  '004370':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  277500    2549  277000  277500  276000
  1   2022-07-20  277500   30147  283500  284000  276500
  2   2022-07-19  283000   15218  279500  284000  277500
  3   2022-07-18  279000   14217  281500  282500  278000
  4   2022-07-15  280500   18808  283000  284000  277500
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  277000   81326  280000  285500  270500
  596 2020-02-24  280000  143180  293000  301000  279000
  597 2020-02-21  281500   74178  276500  286000  276500
  598 2020-02-20  275500   55567  276000  280500  270500
  599 2020-02-19  274000   73065  263000  275500  261000

  [600 rows x 6 columns],
  '005300':             일자      종가    거래량      시가      고가      저가
  0   2022-07-21  171500   3972  173500  174000  171500
  1   2022-07-20  174000  13612  174000  176500  172500
  2   2022-07-19  173500  29041  168500  173500  168000
  3   2022-07-18  168500  29958  170500  172000  167500
  4   2022-07-15  171000  24548  173500  173500  165000
  ..         ...     ...    ...     ...     ...     ...
  595 2020-02-25  116500  16247  116000  118000  115000
  596 2020-02-24  116000  15940  117000  120000  115500
  597 2020-02-21  119000  12991  121500  122000  119000
  598 2020-02-20  122000  14437  123000  124500  120500
  599 2020-02-19  123000   6494  126500  126500  123000

  [600 rows x 6 columns]},
 'Clothing': {'383220':             일자      종가      거래량      시가      고가      저가
  0   2022-07-21  145000    37381  140000  146500  140000
  1   2022-07-20  140000    86060  141500  144500  139000
  2   2022-07-19  139500    48976  138000  142500  138000
  3   2022-07-18  139000    61299  140500  142000  137000
  4   2022-07-15  140500   122342  136000  142000  133500
  ..         ...     ...      ...     ...     ...     ...
  285 2021-05-27   87300   349185   86000   87400   84400
  286 2021-05-26   87300   503055   86000   88600   81200
  287 2021-05-25   86000   514200   88600   89000   83200
  288 2021-05-24   89000   879900   83600   91000   81500
  289 2021-05-21   82500  2774180   72000   93600   72000

  [290 rows x 6 columns],
  '093050':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  17050    9992  17450  17600  17050
  1   2022-07-20  17400   62227  16850  17500  16700
  2   2022-07-19  16850  102588  15700  16900  15550
  3   2022-07-18  15700   21894  15350  15750  15250
  4   2022-07-15  15200   41203  15350  15500  15050
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25  13550  135624  13200  13750  13100
  596 2020-02-24  13250  140847  13400  13650  13200
  597 2020-02-21  13800  149205  13550  13950  13500
  598 2020-02-20  13700  165535  14050  14200  13650
  599 2020-02-19  14000  142040  14550  14550  13900

  [600 rows x 6 columns],
  '020000':             일자     종가    거래량     시가     고가     저가
  0   2022-07-21  30400   9116  29950  30400  29950
  1   2022-07-20  30150  62854  30200  30550  30000
  2   2022-07-19  29900  46879  29150  30050  29150
  3   2022-07-18  29500  58144  29200  29750  28850
  4   2022-07-15  28550  54818  29300  29300  28150
  ..         ...    ...    ...    ...    ...    ...
  595 2020-02-25  25800  79997  24650  26000  24550
  596 2020-02-24  24700  73996  25100  25150  24550
  597 2020-02-21  25750  72465  26800  26800  25750
  598 2020-02-20  26950  57727  27400  27700  26950
  599 2020-02-19  27400  57061  27900  28200  27400

  [600 rows x 6 columns],
  '105630':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  16950   99393  16700  17050  16500
  1   2022-07-20  16700  299231  16950  17400  16600
  2   2022-07-19  16450  227190  16050  16600  15950
  3   2022-07-18  16000  219515  15800  16150  15550
  4   2022-07-15  15650  197073  15850  16050  15400
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25  13800  157226  12950  13850  12900
  596 2020-02-24  13200  207645  13600  13850  13200
  597 2020-02-21  14100  114096  14500  14600  14050
  598 2020-02-20  14600  106809  14900  14900  14550
  599 2020-02-19  14900  146827  15300  15350  14800

  [600 rows x 6 columns],
  '001070':             일자     종가    거래량     시가     고가     저가
  0   2022-07-21  50300  15860  49600  50300  49600
  1   2022-07-20  50000  18173  49450  50000  49250
  2   2022-07-19  49900   1437  49150  49900  49050
  3   2022-07-18  49450   2318  48850  49600  48850
  4   2022-07-15  49150  45220  48750  49150  48000
  ..         ...    ...    ...    ...    ...    ...
  595 2020-02-25  19400   3322  19150  19450  19100
  596 2020-02-24  19200  13708  19650  19850  19200
  597 2020-02-21  19650   3668  19900  19900  19650
  598 2020-02-20  19900   4547  20200  20200  19600
  599 2020-02-19  20050   1777  19750  20200  19750

  [600 rows x 6 columns]},
 'Chemical': {'051910':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  554000  158507  541000  561000  540000
  1   2022-07-20  540000  225805  538000  547000  535000
  2   2022-07-19  521000  161162  525000  530000  517000
  3   2022-07-18  515000  160879  514000  517000  505000
  4   2022-07-15  512000  229151  529000  530000  507000
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  399500  478820  395500  400500  391500
  596 2020-02-24  395000  463848  392000  400000  391500
  597 2020-02-21  407000  400924  407000  416500  406500
  598 2020-02-20  419000  482732  408500  422000  406000
  599 2020-02-19  404000  766920  420500  421500  403500

  [600 rows x 6 columns],
  '096770':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  180500   75843  178000  180500  176500
  1   2022-07-20  178500  256533  179500  180000  176500
  2   2022-07-19  177000  371392  174000  178000  173000
  3   2022-07-18  173000  245629  173500  174000  170000
  4   2022-07-15  170500  329142  172500  174000  166500
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  122500  647578  120000  124000  120000
  596 2020-02-24  123500  531391  126000  127000  123500
  597 2020-02-21  130500  428746  132000  132500  130000
  598 2020-02-20  133000  437224  135500  136000  132000
  599 2020-02-19  135000  432028  137500  138000  134000

  [600 rows x 6 columns],
  '010950':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  93400   91761  93600  94300  92800
  1   2022-07-20  93700  393638  94100  94400  92800
  2   2022-07-19  93200  371087  93300  94900  92400
  3   2022-07-18  92300  373881  89600  92300  88000
  4   2022-07-15  88900  232955  90700  90800  88300
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25  71200  420904  70300  72100  69800
  596 2020-02-24  71600  323598  72000  74200  71600
  597 2020-02-21  74200  234110  75100  75400  74200
  598 2020-02-20  76100  252950  77000  78200  76000
  599 2020-02-19  76800  227356  78900  78900  76500

  [600 rows x 6 columns],
  '051900':             일자       종가    거래량       시가       고가       저가
  0   2022-07-21   719000   7516   724000   727000   717000
  1   2022-07-20   723000  48112   720000   723000   710000
  2   2022-07-19   710000  33057   717000   718000   704000
  3   2022-07-18   717000  32283   713000   725000   712000
  4   2022-07-15   711000  38351   726000   727000   700000
  ..         ...      ...    ...      ...      ...      ...
  595 2020-02-25  1294000  61641  1290000  1309000  1289000
  596 2020-02-24  1278000  67766  1323000  1330000  1275000
  597 2020-02-21  1364000  48179  1373000  1385000  1350000
  598 2020-02-20  1372000  58831  1419000  1426000  1366000
  599 2020-02-19  1410000  26329  1412000  1415000  1390000

  [600 rows x 6 columns],
  '090430':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  136000   64070  137000  137500  134500
  1   2022-07-20  138000  191796  136000  139000  134000
  2   2022-07-19  133500  103096  133000  135000  132500
  3   2022-07-18  134000  117689  134500  136500  133000
  4   2022-07-15  133500  127723  135000  136000  131000
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  175000  449887  173000  176000  171000
  596 2020-02-24  173000  495760  176000  178000  172500
  597 2020-02-21  182000  284559  180000  186500  178500
  598 2020-02-20  183500  418611  188000  190000  182500
  599 2020-02-19  188000  272526  190000  192500  185000

  [600 rows x 6 columns]},
 'Medicine': {'207940':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  818000    8900  820000  826000  817000
  1   2022-07-20  823000   35555  823000  827000  817000
  2   2022-07-19  819000   46882  824000  828000  812000
  3   2022-07-18  810000   46011  813000  817000  803000
  4   2022-07-15  817000   38951  826000  828000  813000
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  473396  249468  453630  473890  452641
  596 2020-02-24  455606  282197  464501  471913  455606
  597 2020-02-21  480808  216625  487232  488220  477349
  598 2020-02-20  492668  264403  501068  507986  489209
  599 2020-02-19  499092  177674  506998  510951  494150

  [600 rows x 6 columns],
  '068270':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  180000  123925  183500  184000  179000
  1   2022-07-20  184000  242433  185000  186500  183000
  2   2022-07-19  183500  223541  184000  186500  182500
  3   2022-07-18  183000  366865  187500  187500  180000
  4   2022-07-15  186500  389861  189500  189500  183000
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  166256  590297  162882  166737  162400
  596 2020-02-24  162882  797541  166256  168183  162882
  597 2020-02-21  170593  465636  170111  174448  169629
  598 2020-02-20  172520  781504  175412  175894  170111
  599 2020-02-19  174930  766613  179267  180231  173484

  [600 rows x 6 columns],
  '302440':             일자      종가       거래량      시가      고가      저가
  0   2022-07-21  131500    197605  135000  135500  131000
  1   2022-07-20  134000    942995  134500  137500  132000
  2   2022-07-19  132500    967387  136000  138000  132000
  3   2022-07-18  134000   1449037  138000  138500  129500
  4   2022-07-15  137000   1902745  143500  145500  135500
  ..         ...     ...       ...     ...     ...     ...
  329 2021-03-24  136500   1707179  138000  142000  135500
  330 2021-03-23  140500   2980953  147000  149500  138000
  331 2021-03-22  144000   4675116  161000  162500  143000
  332 2021-03-19  166500  12468903  184000  190000  166000
  333 2021-03-18  169000    876189  130000  169000  130000

  [334 rows x 6 columns],
  '000100':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  57300   41878  57600  58100  57200
  1   2022-07-20  57900  127748  58600  58600  57500
  2   2022-07-19  58100   99577  57700  58600  57700
  3   2022-07-18  57700  100369  57400  58100  57300
  4   2022-07-15  57300  126581  57500  57800  56600
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25  38838  251381  37831  39205  37831
  596 2020-02-24  37922  229028  38838  39022  37922
  597 2020-02-21  39113  244209  39846  40121  39113
  598 2020-02-20  40304  149318  40304  40670  40121
  599 2020-02-19  40487  156447  40670  40670  40121

  [600 rows x 6 columns],
  '128940':             일자      종가    거래량      시가      고가      저가
  0   2022-07-21  307000  10189  311500  314000  305500
  1   2022-07-20  313000  27469  314000  315500  309000
  2   2022-07-19  310500  37063  307500  314500  305000
  3   2022-07-18  306000  78290  312000  314000  298000
  4   2022-07-15  314000  32823  312000  318000  307000
  ..         ...     ...    ...     ...     ...     ...
  595 2020-02-25  256158  47351  247491  257121  247010
  596 2020-02-24  251343  67388  256158  259529  251343
  597 2020-02-21  265788  42808  269640  270122  265307
  598 2020-02-20  270603  43604  275418  275418  270122
  599 2020-02-19  275418  39406  277826  279270  274455

  [600 rows x 6 columns]},
 'Non_Metal': {'003670':             일자      종가      거래량      시가      고가      저가
  0   2022-07-21  119000    92464  118500  120500  117000
  1   2022-07-20  118000   318270  116000  120000  115500
  2   2022-07-19  113500   188757  111500  115000  110500
  3   2022-07-18  112000   235294  110000  112500  107000
  4   2022-07-15  109000   156374  110500  110500  108000
  ..         ...     ...      ...     ...     ...     ...
  595 2020-02-25   57818   735257   56504   58099   55565
  596 2020-02-24   56034  1051982   53500   57255   53500
  597 2020-02-21   55284   692971   56785   57161   54908
  598 2020-02-20   58099   689808   58193   58287   56222
  599 2020-02-19   57818   632661   59320   59601   56504

  [600 rows x 6 columns],
  '003410':             일자    종가      거래량    시가    고가    저가
  0   2022-07-21  6290    65745  6270  6320  6260
  1   2022-07-20  6290   572728  6350  6420  6260
  2   2022-07-19  6300   268789  6290  6340  6240
  3   2022-07-18  6290   327802  6220  6290  6210
  4   2022-07-15  6210   554727  6170  6230  6010
  ..         ...   ...      ...   ...   ...   ...
  595 2020-02-25  5247  1422905  4952  5264  4952
  596 2020-02-24  4952  2114854  4913  4985  4782
  597 2020-02-21  5028  1401794  5116  5143  5028
  598 2020-02-20  5165  1057469  5269  5280  5154
  599 2020-02-19  5275   719606  5308  5324  5236

  [600 rows x 6 columns],
  '010780':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  40200    7415  40200  40300  39850
  1   2022-07-20  40250  162863  40150  40500  39750
  2   2022-07-19  39800   62032  39150  40350  39150
  3   2022-07-18  39300   61481  38450  39900  38200
  4   2022-07-15  38100   35393  39100  39500  37600
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25  27900   87964  26950  28050  26700
  596 2020-02-24  26700   97795  27750  28100  26700
  597 2020-02-21  28100   47793  28500  28750  28100
  598 2020-02-20  28550   40636  28750  29250  28550
  599 2020-02-19  28900   30715  28900  29300  28700

  [600 rows x 6 columns],
  '300720':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  13550   14084  13450  13600  13300
  1   2022-07-20  13400   65133  13500  13650  13250
  2   2022-07-19  13250   27012  13050  13350  13050
  3   2022-07-18  13250   66894  13050  13300  12800
  4   2022-07-15  12850  122495  13150  13250  12400
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25   7520   21190   7170   7540   7170
  596 2020-02-24   7260   42460   7500   7500   7230
  597 2020-02-21   7520   35110   7740   7780   7510
  598 2020-02-20   7740   44960   7800   7910   7630
  599 2020-02-19   7900   36180   8070   8070   7760

  [600 rows x 6 columns]},
 'Metal': {'005490':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  229500   44837  230000  231000  228000
  1   2022-07-20  232000  199103  234000  234000  230500
  2   2022-07-19  230000  273542  226500  230500  225500
  3   2022-07-18  226500  273744  226000  227000  222000
  4   2022-07-15  224000  298831  225000  228000  221500
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  202000  306873  201000  203500  201000
  596 2020-02-24  203500  337423  207000  208000  202000
  597 2020-02-21  211500  217235  213500  214000  211000
  598 2020-02-20  215500  203605  217000  218500  214000
  599 2020-02-19  216500  190216  219000  220000  216000

  [600 rows x 6 columns],
  '010130':             일자      종가     거래량      시가      고가      저가
  0   2022-07-21  455000    7156  456000  457500  453500
  1   2022-07-20  457500   39108  461000  461500  453000
  2   2022-07-19  456500   23273  458500  463000  455000
  3   2022-07-18  460000   36699  451000  460000  447500
  4   2022-07-15  450000   20009  454000  455000  445000
  ..         ...     ...     ...     ...     ...     ...
  595 2020-02-25  427500   46681  429000  431000  416000
  596 2020-02-24  426000   48775  431000  440000  426000
  597 2020-02-21  440000   47327  444500  451500  440000
  598 2020-02-20  448000   64515  458000  461000  448000
  599 2020-02-19  461000  110265  445500  463500  441000

  [600 rows x 6 columns],
  '004020':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  33150   91318  32700  33250  32600
  1   2022-07-20  33050  415165  33150  33300  32750
  2   2022-07-19  32600  342684  32000  32750  31900
  3   2022-07-18  32100  382662  31700  32150  31350
  4   2022-07-15  31400  344704  31900  32000  30650
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25  25500  521684  25100  25800  25100
  596 2020-02-24  25450  713587  26250  26250  25450
  597 2020-02-21  26950  551952  27650  27650  26900
  598 2020-02-20  27650  509621  28450  28550  27600
  599 2020-02-19  28300  365808  28850  29050  28250

  [600 rows x 6 columns],
  '016380':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  12600  121028  12750  12750  12550
  1   2022-07-20  12750  574238  12900  13050  12600
  2   2022-07-19  12550  476257  12500  12750  12350
  3   2022-07-18  12500  499316  12400  12600  12300
  4   2022-07-15  12200  698279  12650  12700  12000
  ..         ...    ...     ...    ...    ...    ...
  595 2020-02-25   7170    3433   7100   7260   7090
  596 2020-02-24   7230   22391   7290   7290   7010
  597 2020-02-21   7290   25951   7280   7390   7170
  598 2020-02-20   7200    9687   7140   7340   7140
  599 2020-02-19   7270    3535   7190   7310   7150

  [600 rows x 6 columns],
  '001230':             일자     종가     거래량     시가     고가     저가
  0   2022-07-21  12700   91848  12600  12750  12500
  1   2022-07-20  12650  275738  12800  12900  12600
  2   2022-07-19  12550  233012  12350  12550  12250
  3   2022-07-18  12400  386195  12150  12450  12000

# 이전 data와 최신 data 병합(최신화)

In [ ]:
'''
df_sector_3 = {'Food':{},
          'Clothing' : {},
          'Chemical' : {},
          'Medicine' : {},
          'Non_Metal' : {},
          'Metal': {},
          'Machine' : {},
          'Electronic' : {},
          'Construction' : {},
          'Transport': {},
          'Distribution' : {},
          'Power': {},
          'Tele' : {},
          'Finance': {},
          'Brokerage' : {},
          'Insurer': {},
          'Service': {},
          'Manufacturer': {}}
'''

In [15]:
for sector_name, df_dict in df_sector.items():
    for stockcode, df in df_dict.items():
        df = pd.concat([df_sector[sector_name][stockcode],df])
        df=df.drop_duplicates(subset=['일자'])
        df = df.reset_index(drop=True)
        df_sector[sector_name][stockcode] = df

In [16]:
df_sector

{'Food': {'097950':              일자      종가    거래량      시가      고가      저가
  0    2022-07-21  395500   4227  397000  397500  394000
  1    2022-07-20  396500  39486  402000  403000  395500
  2    2022-07-19  405000  41409  393000  405000  390000
  3    2022-07-18  391000  27816  396000  399000  389000
  4    2022-07-15  397500  40227  395000  401000  381000
  ...         ...     ...    ...     ...     ...     ...
  2995 2010-06-01  211000  31617  214000  215000  210000
  2996 2010-05-31  214000  30990  215000  215000  211500
  2997 2010-05-28  213000  64458  211500  213000  208000
  2998 2010-05-27  211500  46323  208500  212000  205000
  2999 2010-05-26  213500  77164  212500  213500  203500

  [3000 rows x 6 columns],
  '271560':              일자      종가      거래량      시가      고가      저가
  0    2022-07-21  101500    26597  101500  103000  101500
  1    2022-07-20  102000   157611  106000  106500  101500
  2    2022-07-19  105000   119285  104000  106000  102500
  3    2022-07-18  104000   140201  106500  107000  103500
  4    2022-07-15  106500    90893  108500  108500  104000
  ...         ...     ...      ...     ...     ...     ...
  1234 2017-07-13   81600   218138   83400   84000   80800
  1235 2017-07-12   83500   238407   83700   84600   80000
  1236 2017-07-11   82800   422303   88000   88000   82700
  1237 2017-07-10   88000   840451   82300   88000   81000
  1238 2017-07-07   82300  1619864   87100   89700   75700

  [1239 rows x 6 columns],
  '000080':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  29650   43306  29700  29800  29600
  1    2022-07-20  29800  175862  30050  30250  29700
  2    2022-07-19  29800  127612  29650  30150  29400
  3    2022-07-18  29600  173327  29250  29750  29200
  4    2022-07-15  29300  210606  30000  30000  28950
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01  33200   89108  33050  33850  32950
  2996 2010-05-31  33050  103839  31700  33300  31700
  2997 2010-05-28  31550  117860  32400  32500  31400
  2998 2010-05-27  32050  262075  31400  34900  31150
  2999 2010-05-26  31400  123593  31300  31400  30550

  [3000 rows x 6 columns],
  '004370':              일자      종가    거래량      시가      고가      저가
  0    2022-07-21  277500   2549  277000  277500  276000
  1    2022-07-20  277500  30147  283500  284000  276500
  2    2022-07-19  283000  15218  279500  284000  277500
  3    2022-07-18  279000  14217  281500  282500  278000
  4    2022-07-15  280500  18808  283000  284000  277500
  ...         ...     ...    ...     ...     ...     ...
  2995 2010-06-01  230000   7402  226500  230000  226500
  2996 2010-05-31  228000   7356  232000  233000  225500
  2997 2010-05-28  225500   7628  227000  227000  224500
  2998 2010-05-27  228000   8793  227000  230000  225000
  2999 2010-05-26  227500  14811  223500  230500  222500

  [3000 rows x 6 columns],
  '005300':              일자      종가    거래량      시가      고가      저가
  0    2022-07-21  171500   3972  173500  174000  171500
  1    2022-07-20  174000  13612  174000  176500  172500
  2    2022-07-19  173500  29041  168500  173500  168000
  3    2022-07-18  168500  29958  170500  172000  167500
  4    2022-07-15  171000  24548  173500  173500  165000
  ...         ...     ...    ...     ...     ...     ...
  2995 2010-06-01   78900  15030   78700   79700   78600
  2996 2010-05-31   78700  23650   79300   80700   78600
  2997 2010-05-28   78700  20540   78600   81400   78200
  2998 2010-05-27   78500  18190   77100   79000   77000
  2999 2010-05-26   78500  22910   76200   79700   76200

  [3000 rows x 6 columns]},
 'Clothing': {'383220':             일자      종가      거래량      시가      고가      저가
  0   2022-07-21  145000    37381  140000  146500  140000
  1   2022-07-20  140000    86060  141500  144500  139000
  2   2022-07-19  139500    48976  138000  142500  138000
  3   2022-07-18  139000    61299  140500  142000  137000
  4   2022-07-15  140500   122342  136000  142000  133500
  ..         ...     ...      ...     ...     ...     ...
  285 2021-05-27   87300   349185   86000   87400   84400
  286 2021-05-26   87300   503055   86000   88600   81200
  287 2021-05-25   86000   514200   88600   89000   83200
  288 2021-05-24   89000   879900   83600   91000   81500
  289 2021-05-21   82500  2774180   72000   93600   72000

  [290 rows x 6 columns],
  '093050':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  17050    9992  17450  17600  17050
  1    2022-07-20  17400   62227  16850  17500  16700
  2    2022-07-19  16850  102588  15700  16900  15550
  3    2022-07-18  15700   21894  15350  15750  15250
  4    2022-07-15  15200   41203  15350  15500  15050
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01  25350  236384  26050  26200  25200
  2996 2010-05-31  26350  166055  25950  26350  25400
  2997 2010-05-28  25700  176589  25800  26200  25500
  2998 2010-05-27  25700  269920  26000  26000  25050
  2999 2010-05-26  25750   95745  26100  26400  25700

  [3000 rows x 6 columns],
  '020000':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  30400    9116  29950  30400  29950
  1    2022-07-20  30150   62854  30200  30550  30000
  2    2022-07-19  29900   46879  29150  30050  29150
  3    2022-07-18  29500   58144  29200  29750  28850
  4    2022-07-15  28550   54818  29300  29300  28150
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01  14050   81101  14350  14350  14000
  2996 2010-05-31  14300   87060  14000  14450  14000
  2997 2010-05-28  14100  106458  14100  14150  13700
  2998 2010-05-27  13950  161885  14200  14500  13800
  2999 2010-05-26  14400   54425  14400  14550  14000

  [3000 rows x 6 columns],
  '105630':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  16950   99393  16700  17050  16500
  1    2022-07-20  16700  299231  16950  17400  16600
  2    2022-07-19  16450  227190  16050  16600  15950
  3    2022-07-18  16000  219515  15800  16150  15550
  4    2022-07-15  15650  197073  15850  16050  15400
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01   5757  135918   6050   6117   5720
  2996 2010-05-31   6110   65822   6230   6230   6027
  2997 2010-05-28   6147  181957   6350   6350   6117
  2998 2010-05-27   6350  170703   6155   6380   5855
  2999 2010-05-26   6230  132346   5967   6298   5855

  [3000 rows x 6 columns],
  '001070':              일자     종가    거래량     시가     고가     저가
  0    2022-07-21  50300  15860  49600  50300  49600
  1    2022-07-20  50000  18173  49450  50000  49250
  2    2022-07-19  49900   1437  49150  49900  49050
  3    2022-07-18  49450   2318  48850  49600  48850
  4    2022-07-15  49150  45220  48750  49150  48000
  ...         ...    ...    ...    ...    ...    ...
  2995 2010-06-01   5300   2550   5280   5300   5120
  2996 2010-05-31   5290   2550   5060   5300   5060
  2997 2010-05-28   5060  11050   5290   5290   5060
  2998 2010-05-27   5230   6150   5180   5400   5100
  2999 2010-05-26   5090  14905   4970   5100   4810

  [3000 rows x 6 columns]},
 'Chemical': {'051910':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21  554000  158507  541000  561000  540000
  1    2022-07-20  540000  225805  538000  547000  535000
  2    2022-07-19  521000  161162  525000  530000  517000
  3    2022-07-18  515000  160879  514000  517000  505000
  4    2022-07-15  512000  229151  529000  530000  507000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  272000  218930  271500  274500  267000
  2996 2010-05-31  273000  247644  270000  277000  267000
  2997 2010-05-28  270000  412162  274500  276000  264000
  2998 2010-05-27  272000  305893  265000  275000  263500
  2999 2010-05-26  268500  423060  261500  271000  259500

  [3000 rows x 6 columns],
  '096770':              일자      종가      거래량      시가      고가      저가
  0    2022-07-21  180500    75843  178000  180500  176500
  1    2022-07-20  178500   256533  179500  180000  176500
  2    2022-07-19  177000   371392  174000  178000  173000
  3    2022-07-18  173000   245629  173500  174000  170000
  4    2022-07-15  170500   329142  172500  174000  166500
  ...         ...     ...      ...     ...     ...     ...
  2995 2010-06-01  108000   557598  107500  108500  104500
  2996 2010-05-31  108500   686012  107500  111000  106500
  2997 2010-05-28  107500  1548069  105000  109000  103500
  2998 2010-05-27  100500   904128   97300  101500   96500
  2999 2010-05-26   97100   942247   99900   99900   94300

  [3000 rows x 6 columns],
  '010950':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  93400   91761  93600  94300  92800
  1    2022-07-20  93700  393638  94100  94400  92800
  2    2022-07-19  93200  371087  93300  94900  92400
  3    2022-07-18  92300  373881  89600  92300  88000
  4    2022-07-15  88900  232955  90700  90800  88300
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01  52000  154475  51300  52500  51100
  2996 2010-05-31  51700  152228  50900  51800  50500
  2997 2010-05-28  50900  291916  50100  50900  49450
  2998 2010-05-27  49150  346735  49600  49700  49000
  2999 2010-05-26  49650  195898  50000  51100  49650

  [3000 rows x 6 columns],
  '051900':              일자      종가    거래량      시가      고가      저가
  0    2022-07-21  719000   7516  724000  727000  717000
  1    2022-07-20  723000  48112  720000  723000  710000
  2    2022-07-19  710000  33057  717000  718000  704000
  3    2022-07-18  717000  32283  713000  725000  712000
  4    2022-07-15  711000  38351  726000  727000  700000
  ...         ...     ...    ...     ...     ...     ...
  2995 2010-06-01  325000  24899  317500  331000  316000
  2996 2010-05-31  319000  25797  316000  323500  316000
  2997 2010-05-28  316000  45378  306000  317500  303000
  2998 2010-05-27  306000  43499  305000  309500  301000
  2999 2010-05-26  305500  23804  302000  309000  302000

  [3000 rows x 6 columns],
  '090430':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21  136000   64070  137000  137500  134500
  1    2022-07-20  138000  191796  136000  139000  134000
  2    2022-07-19  133500  103096  133000  135000  132500
  3    2022-07-18  134000  117689  134500  136500  133000
  4    2022-07-15  133500  127723  135000  136000  131000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01   93800   72990   90800   93800   90600
  2996 2010-05-31   91700   86570   91100   92900   90600
  2997 2010-05-28   91800  149120   92400   92400   89500
  2998 2010-05-27   91000  139430   90200   92500   89100
  2999 2010-05-26   91500  132680   90000   91500   89000

  [3000 rows x 6 columns]},
 'Medicine': {'207940':              일자      종가      거래량      시가      고가      저가
  0    2022-07-21  818000     8900  820000  826000  817000
  1    2022-07-20  823000    35555  823000  827000  817000
  2    2022-07-19  819000    46882  824000  828000  812000
  3    2022-07-18  810000    46011  813000  817000  803000
  4    2022-07-15  817000    38951  826000  828000  813000
  ...         ...     ...      ...     ...     ...     ...
  1396 2016-11-16  168011  1680639  166529  170976  161587
  1397 2016-11-15  164058  2623646  176906  179376  160599
  1398 2016-11-14  173447  3012422  163070  175423  163070
  1399 2016-11-11  159610  8236911  147751  184318  140339
  1400 2016-11-10  142315  7264007  133421  146268  124032

  [1401 rows x 6 columns],
  '068270':              일자      종가      거래량      시가      고가      저가
  0    2022-07-21  180000   123925  183500  184000  179000
  1    2022-07-20  184000   242433  185000  186500  183000
  2    2022-07-19  183500   223541  184000  186500  182500
  3    2022-07-18  183000   366865  187500  187500  180000
  4    2022-07-15  186500   389861  189500  189500  183000
  ...         ...     ...      ...     ...     ...     ...
  2995 2010-06-01   18572   956074   18705   18972   18350
  2996 2010-05-31   18927  1050816   18661   18927   18305
  2997 2010-05-28   18572  2912063   18172   18838   18083
  2998 2010-05-27   17772  1340352   17150   17772   16928
  2999 2010-05-26   17417  1753427   17194   17461   16661

  [3000 rows x 6 columns],
  '302440':             일자      종가       거래량      시가      고가      저가
  0   2022-07-21  131500    197605  135000  135500  131000
  1   2022-07-20  134000    942995  134500  137500  132000
  2   2022-07-19  132500    967387  136000  138000  132000
  3   2022-07-18  134000   1449037  138000  138500  129500
  4   2022-07-15  137000   1902745  143500  145500  135500
  ..         ...     ...       ...     ...     ...     ...
  329 2021-03-24  136500   1707179  138000  142000  135500
  330 2021-03-23  140500   2980953  147000  149500  138000
  331 2021-03-22  144000   4675116  161000  162500  143000
  332 2021-03-19  166500  12468903  184000  190000  166000
  333 2021-03-18  169000    876189  130000  169000  130000

  [334 rows x 6 columns],
  '000100':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  57300   41878  57600  58100  57200
  1    2022-07-20  57900  127748  58600  58600  57500
  2    2022-07-19  58100   99577  57700  58600  57700
  3    2022-07-18  57700  100369  57400  58100  57300
  4    2022-07-15  57300  126581  57500  57800  56600
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01  21844  129918  21477  21844  21256
  2996 2010-05-31  21550  254568  21109  21771  20962
  2997 2010-05-28  21182  268899  21182  21256  20815
  2998 2010-05-27  21182  308756  20741  21403  20520
  2999 2010-05-26  20668  581890  21477  21771  20668

  [3000 rows x 6 columns],
  '128940':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21  307000   10189  311500  314000  305500
  1    2022-07-20  313000   27469  314000  315500  309000
  2    2022-07-19  310500   37063  307500  314500  305000
  3    2022-07-18  306000   78290  312000  314000  298000
  4    2022-07-15  314000   32823  312000  318000  307000
  ...         ...     ...     ...     ...     ...     ...
  2949 2010-08-05   56654  114537   59552   59552   56268
  2950 2010-08-04   58715   99727   58715   60002   55367
  2951 2010-08-03   58715   57060   58715   59873   58586
  2952 2010-08-02   58586  159281   63414   63672   58264
  2953 2010-07-30   64316  383395   57942   66633   57942

  [2954 rows x 6 columns]},
 'Non_Metal': {'003670':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21  119000   92464  118500  120500  117000
  1    2022-07-20  118000  318270  116000  120000  115500
  2    2022-07-19  113500  188757  111500  115000  110500
  3    2022-07-18  112000  235294  110000  112500  107000
  4    2022-07-15  109000  156374  110500  110500  108000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01    7144  138936    6956    7172    6862
  2996 2010-05-31    6881   74819    6956    6956    6721
  2997 2010-05-28    6909  125223    7323    7323    6834
  2998 2010-05-27    6984  100128    6918    7041    6909
  2999 2010-05-26    6965  248234    7041    7041    6853

  [3000 rows x 6 columns],
  '003410':              일자    종가     거래량    시가    고가    저가
  0    2022-07-21  6290   65745  6270  6320  6260
  1    2022-07-20  6290  572728  6350  6420  6260
  2    2022-07-19  6300  268789  6290  6340  6240
  3    2022-07-18  6290  327802  6220  6290  6210
  4    2022-07-15  6210  554727  6170  6230  6010
  ...         ...   ...     ...   ...   ...   ...
  2995 2010-06-01  1151  632132  1131  1162  1131
  2996 2010-05-31  1146  445630  1144  1172  1125
  2997 2010-05-28  1159  521564  1183  1183  1149
  2998 2010-05-27  1162  311749  1149  1175  1149
  2999 2010-05-26  1181  361744  1170  1201  1149

  [3000 rows x 6 columns],
  '010780':              일자     종가     거래량     시가     고가     저가
  0    2022-07-21  40200    7415  40200  40300  39850
  1    2022-07-20  40250  162863  40150  40500  39750
  2    2022-07-19  39800   62032  39150  40350  39150
  3    2022-07-18  39300   61481  38450  39900  38200
  4    2022-07-15  38100   35393  39100  39500  37600
  ...         ...    ...     ...    ...    ...    ...
  2995 2010-06-01   5852   31363   5788   5942   5788
  2996 2010-05-31   5827   53638   5891   5910   5795
  2997 2010-05-28   5852   50016   6140   6191   5795
  2998 2010-05-27   6076  129096   5501   6076   5437
  2999 2010-05-26   5424   14484   5501   5501   5360

  [3000 rows x 6 columns],
  '300720':             일자     종가      거래량     시가     고가     저가
  0   2022-07-21  13550    14084  13450  13600  13300
  1   2022-07-20  13400    65133  13500  13650  13250
  2   2022-07-19  13250    27012  13050  13350  13050
  3   2022-07-18  13250    66894  13050  13300  12800
  4   2022-07-15  12850   122495  13150  13250  12400
  ..         ...    ...      ...    ...    ...    ...
  971 2018-08-10  12150   469820  12150  12300  11850
  972 2018-08-09  11650   413900  12150  12150  11500
  973 2018-08-08  12150   643900  12300  12600  11750
  974 2018-08-07  12150  1889920  12300  14250  11700
  975 2018-08-06  11900  2694870  14450  18400  11700

  [976 rows x 6 columns]},
 'Metal': {'005490':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21  229500   44837  230000  231000  228000
  1    2022-07-20  232000  199103  234000  234000  230500
  2    2022-07-19  230000  273542  226500  230500  225500
  3    2022-07-18  226500  273744  226000  227000  222000
  4    2022-07-15  224000  298831  225000  228000  221500
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  460000  266996  468000  470000  457500
  2996 2010-05-31  472000  182932  471000  473500  465500
  2997 2010-05-28  472000  292027  474500  474500  465500
  2998 2010-05-27  464500  391049  457000  470000  454500
  2999 2010-05-26  454500  427735  455000  463500  451000

  [3000 rows x 6 columns],
  '010130':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21  455000    7156  456000  457500  453500
  1    2022-07-20  457500   39108  461000  461500  453000
  2    2022-07-19  456500   23273  458500  463000  455000
  3    2022-07-18  460000   36699  451000  460000  447500
  4    2022-07-15  450000   20009  454000  455000  445000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  195500   67772  196500  196500  192500
  2996 2010-05-31  197500   39725  193500  197500  192000
  2997 2010-05-28  193500   97307  197500  198000  190500
  2998 2010-05-27  193000  112336  186000  194000  184000
  2999 2010-05-26  186000   89574  186500  191000  184500

  [3000 rows x 6 columns],
  '004020':              일자     종가      거래량     시가     고가     저가
  0    2022-07-21  33150    91318  32700  33250  32600
  1    2022-07-20  33050   415165  33150  33300  32750
  2    2022-07-19  32600   342684  32000  32750  31900
  3    2022-07-18  32100   382662  31700  32150  31350
  4    2022-07-15  31400   344704  31900  32000  30650
  ...         ...    ...      ...    ...    ...    ...
  2995 2010-06-01  87500   318099  88100  88500  86700
  2996 2010-05-31  88200   335238  87100  88300  87100
  2997 2010-05-28  87900   746510  88200  89300  87500
  2998 2010-05-27  87000   870363  84200  88500  84000
  2999 2010-05-26  85500  1043037  82800  85500  82600

  [3000 rows x 6 columns],
  '016380':              일자      종가     거래량      시가      고가      저가
  0    2022-07-21   12600  121028   12750   12750   12550
  1    2022-07-20   12750  574238   12900   13050   12600
  2    2022-07-19   12550  476257   12500   12750   12350
  3    2022-07-18   12500  499316   12400   12600   12300
  4    2022-07-15   12200  698279   12650   12700   12000
  ...         ...     ...     ...     ...     ...     ...
  2995 2010-06-01  492531    3735  502670  502670  489863
  2996 2010-05-31  496800    3643  490930  503204  485594
  2997 2010-05-28  496267    5994  498935  507473  491464
  2998 2010-05-27  487729    6400  477056  492531  474922

# 최신 kospi 수집

In [ ]:
'''
def Add_Kospi():
    df = kiwoom.block_request("opt20006",
                              업종코드="001",
                              기준일자=set_d,
                              output="업종일봉조회",
                              next=0)
    df = df[['일자','현재가']]
    df2 = pd.DataFrame()
    df2['일자'] = pd.to_datetime(df['일자'])
    df2['코스피지수'] = df['현재가'].astype(int)
    df2['코스피지수'] = df2['코스피지수'].apply(lambda x : x/100)
    return df2    
    
'''

In [ ]:
#kospi2 = Add_Kospi()

In [ ]:
#kospi2

# 이전 kospi와 최신 kospi 병합(최신화)

In [ ]:
#kospi3 = pd.concat([kospi2,kospi])
#kospi3=kospi3.drop_duplicates(subset=['일자'])
#kospi3 = kospi3.reset_index(drop=True)

In [ ]:
#kospi3

In [17]:
with open('df_sector_UTD.pickle','wb') as f:
    pickle.dump(df_sector,f)

In [ ]:
# with open('kospi.pickle','wb') as f:
#     pickle.dump(kospi3,f)